(function(){
  const S=window.V7SStateV7s,T=window.TreasureHunterDataV7s,D=window.V7SDerived;if(!S||!T||!D)return;
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),signed=n=>Number(n)>=0?`+${Number(n)}`:`${Number(n)}`;
  const open=new Set(),ATTACK_FEATURES=new Set(['object-manipulation','snatch-item','attack-slide','precision-slide','line-attack','rope-snare','rope-takedown','daring-strike','improved-attack-slide','improved-daring','superior-daring','legendary-slide','at-right-moment']),FREE_FEATURES=new Set(['attack-slide','precision-slide','line-attack','rope-pull','rope-takedown']);
  const PARENT={'attack-slide':'indy-slide','precision-slide':'attack-slide','line-attack':'attack-slide','improved-attack-slide':'attack-slide','improved-slide':'indy-slide','legendary-slide':'indy-slide','rope-pull':'rope-snare','rope-takedown':'rope-snare','quick-rope':'rope-snare'};
  const CORE=[
    ['core-attack','Attack',true,'Make one attack with a weapon or Unarmed Strike.'],['core-unarmed','Unarmed Strike — Damage',true,'Make a melee attack using Strength and Proficiency Bonus.'],['core-grapple','Grapple',true,'Use an Unarmed Strike to attempt a Grapple.'],['core-shove','Shove / Push',true,'Use an Unarmed Strike to push a target 5 ft. away or knock it Prone.'],['core-dash','Dash',false,'Gain extra movement for this turn equal to your Speed.'],['core-disengage','Disengage',false,'Your movement does not provoke Opportunity Attacks for the rest of the turn.'],['core-dodge','Dodge',false,'Attacks against you have Disadvantage if you can see the attacker, and you make DEX saves with Advantage until your next turn.'],['core-help','Help',false,'Assist another creature with a check or attack.'],['core-hide','Hide',false,'Attempt to become hidden.'],['core-influence','Influence',false,'Try to influence another creature.'],['core-magic','Magic',false,'Cast a spell, use a magic item, or activate a magical feature.'],['core-ready','Ready',false,'Choose a trigger and prepare an action for your Reaction.'],['core-search','Search',false,'Use an appropriate ability or skill to find something concealed.'],['core-study','Study',false,'Use an appropriate Intelligence-based check to recall or discover useful information.'],['core-utilize','Utilize',false,'Use a nonmagical object whose use requires an action.']
  ].map(([id,name,attack,summary])=>({id,name,action:'Action',group:'core',source:'Core',attack,summary}));
  CORE.push({id:'core-object',name:'Simple Object Interaction',action:'Free',group:'core',source:'Core',summary:'A simple interaction such as drawing, stowing, opening, or handling an object can often be done without an Action.'});
  const state=()=>S.get(),pb=()=>D.pb(),level=()=>D.level(),code=a=>a==='Action'?'A':a==='Bonus Action'?'BA':a==='Reaction'?'R':a==='Free'?'FREE':a==='Other'?'OTHER':'PASS',badge=a=>({A:'a',BA:'ba',R:'r',FREE:'free',OTHER:'other'}[code(a)]||'pass');
  function relicRows(){return (state().classes.treasureHunter.relics||[]).map((x,i)=>typeof x==='string'?{id:x,prepared:false,used:0,stateIndex:i}:{prepared:false,used:0,...x,stateIndex:i}).map(x=>({...((T.relics||[]).find(r=>r.id===x.id)||{}),...x})).filter(Boolean)}
  function relicMax(r){return r.uses==='PB'?pb():Math.max(0,Number(r.charges)||0)}
  function weapons(){return (state().character.gear.weapons||[]).map(w=>({id:`weapon-${w.id||w.name}`,name:w.name,action:'Action',group:'weapon',source:'Weapon',attack:true,summary:`Attack ${signed(D.mod(w.attackAbility||'DEX')+pb())} • ${w.damage||''} ${w.damageType||''} ${signed(D.mod(w.attackAbility||'DEX'))}${w.mastery?` • Mastery: ${w.mastery}`:''}`}))}
  function spells(){return (state().character.spells||[]).filter(x=>x&&x.prepared!==false).map((x,i)=>({id:`spell-${x.id||i}`,name:x.name||'Spell',action:x.action||'Action',group:'spell',source:'Spell',attack:!!x.attack,summary:x.summary||x.description||'',detail:x.description||x.summary||''}))}
  function relics(){return relicRows().filter(r=>r.prepared&&r.action&&r.action!=='Passive').map(r=>({id:`relic-${r.id}`,name:r.name,action:r.action,group:'relic',source:'Relic',summary:r.summary||r.fullText||'',detail:r.fullText||r.summary||'',relicIndex:r.stateIndex,relicMax:relicMax(r),relicUsed:Number(r.used)||0,attack:/attack|útok|zásah/i.test(r.fullText||'')}))}
  function features(){const out=[];(T.features||[]).filter(f=>f.level<=level()).forEach(f=>{if(f.action&&!['Passive','Resource'].includes(f.action))out.push({id:`feature-${f.id}`,featureId:f.id,name:f.name,action:FREE_FEATURES.has(f.id)?'Free':f.action,group:'class',source:'Treasure Hunter',summary:f.summary||f.fullText||'',detail:f.fullText||f.summary||'',cost:Number(f.cost)||0,uses:Number(f.uses)||0,parent:PARENT[f.id]||'',attack:ATTACK_FEATURES.has(f.id)});(f.actions||[]).forEach((a,i)=>out.push({id:`feature-${f.id}-${a.id||i}`,featureId:f.id,name:a.name||f.name,action:a.action||'Action',group:'class',source:f.name,summary:a.summary||a.fullText||'',detail:a.fullText||a.summary||'',cost:Number(a.cost??f.cost)||0,uses:Number(a.uses??f.uses)||0,parent:PARENT[f.id]||'',attack:ATTACK_FEATURES.has(f.id)||/attack|útok/i.test(`${a.name} ${a.summary||''}`)}))});return out}
  function custom(){return (state().character.customActions||[]).map((a,i)=>({...a,id:a.id||`custom-${i}`,group:'custom',source:a.source||'Custom',custom:true,attack:!!a.attack}))}
  function all(){return [...weapons(),...spells(),...relics(),...features(),...CORE,...custom()]}
  function match(a,f){if(f==='all')return true;if(f==='attack')return !!a.attack;if(f==='a')return a.action==='Action';if(f==='ba')return a.action==='Bonus Action';if(f==='r')return a.action==='Reaction';if(f==='free')return a.action==='Free';if(f==='other')return a.action==='Other';return true}
  function dots(max,used,attrs){if(!max)return'';const left=Math.max(0,max-used);return `<div class="action-resource"><span>${left}/${max}</span><div class="action-resource-dots">${Array.from({length:max},(_,i)=>`<button type="button" class="action-charge-dot ${i<left?'filled':''}" ${attrs} data-charge-state="${i<left?'full':'empty'}"></button>`).join('')}</div></div>`}
  function resource(a){let h='';if(a.uses){const used=Number(state().classes.treasureHunter.featureUses?.[a.featureId])||0;h+=dots(a.uses,used,`data-actions-feature="${esc(a.featureId)}"`)}if(a.relicMax)h+=dots(a.relicMax,a.relicUsed,`data-actions-relic="${a.relicIndex}"`);if(a.cost)h+=`<button type="button" class="action-cool-spend" data-actions-cool="${a.cost}">−${a.cost} Cool</button>`;return h}
  function card(a,kids,favs){const fav=favs.includes(a.id),r=resource(a),linked=kids.length?`<div class="linked-actions"><span class="linked-label">WITH THIS</span>${kids.map(k=>`<div class="linked-action"><span><b>${esc(k.name)}</b><small>${esc(k.summary||'')}</small></span><span class="badge ${badge(k.action)}">${code(k.action)}</span>${resource(k)}</div>`).join('')}</div>`:'';return `<article class="action-quick-card ${open.has(a.id)?'open':''}"><div class="action-quick-head"><button type="button" class="action-favorite ${fav?'on':''}" data-actions-fav="${esc(a.id)}">★</button><button type="button" class="action-expand" data-actions-open="${esc(a.id)}"><span><strong>${esc(a.name)}</strong><small>${esc(a.source||'')}</small></span><span class="badge ${badge(a.action)}">${code(a.action)}</span></button></div>${r?`<div class="action-resource-strip">${r}</div>`:''}${linked}<div class="action-quick-detail"><p>${esc(a.detail||a.summary||'')}</p>${a.custom?`<button type="button" class="small-btn danger" data-actions-delete="${esc(a.id)}">Delete custom action</button>`:''}</div></article>`}
  function render(){const root=$('#actionsPage');if(!root)return;const ui=state().ui||(state().ui={}),filter=ui.actionFilter||'all',sort=ui.actionSort||'grouped',favs=ui.favoriteActions||[],items=all(),children={};items.filter(x=>x.parent).forEach(x=>(children[x.parent]||(children[x.parent]=[])).push(x));let rows=items.filter(x=>!x.parent&&match(x,filter));items.filter(x=>!x.parent).forEach(p=>{if(!rows.includes(p)&&(children[p.featureId]||[]).some(k=>match(k,filter)))rows.push(p)});let body='';const groups=[['weapon','WEAPON ATTACKS'],['spell','SPELLS'],['relic','RELICS'],['class','TREASURE HUNTER'],['core','CORE ACTIONS'],['custom','CUSTOM']];if(filter==='all'&&sort==='grouped'){const pin=rows.filter(x=>favs.includes(x.id));if(pin.length)body+=`<div class="action-group"><h3>FAVORITES</h3><div class="action-quick-list">${pin.sort((a,b)=>a.name.localeCompare(b.name)).map(a=>card(a,children[a.featureId]||[],favs)).join('')}</div></div>`;groups.forEach(([g,l])=>{const q=rows.filter(x=>x.group===g&&!favs.includes(x.id));if(q.length)body+=`<div class="action-group"><h3>${l}</h3><div class="action-quick-list">${q.sort((a,b)=>a.name.localeCompare(b.name)).map(a=>card(a,children[a.featureId]||[],favs)).join('')}</div></div>`})}else{rows.sort(sort==='name'?(a,b)=>a.name.localeCompare(b.name):sort==='source'?(a,b)=>String(a.source).localeCompare(String(b.source))||a.name.localeCompare(b.name):(a,b)=>(favs.includes(a.id)?0:1)-(favs.includes(b.id)?0:1)||a.name.localeCompare(b.name));body=`<div class="action-quick-list">${rows.map(a=>card(a,children[a.featureId]||[],favs)).join('')||'<div class="empty">No actions in this group.</div>'}</div>`}const filters=[['all','ALL'],['attack','ATTACKS'],['a','A'],['ba','BA'],['r','R'],['free','FREE'],['other','OTHER']].map(([k,l])=>`<button type="button" class="filter-btn ${filter===k?'active':''}" data-actions-filter="${k}">${l}</button>`).join('');root.innerHTML=`<div class="page-intro"><span>ACTIONS</span><small>Fast-use actions; Features is progression</small></div><section class="section"><div class="section-head"><h2>Actions</h2><select class="action-sort" data-actions-sort><option value="grouped" ${sort==='grouped'?'selected':''}>Grouped</option><option value="name" ${sort==='name'?'selected':''}>A–Z</option><option value="source" ${sort==='source'?'selected':''}>Source</option></select></div><div class="filters">${filters}</div><div class="action-toolbar-row"><button type="button" class="small-btn primary" data-new-action>+ Custom Action</button><span class="muted">Favorites always sort first.</span></div>${body}</section>`}
  function featureUse(id,st){const f=(T.features||[]).find(x=>x.id===id),max=Number(f?.uses)||1,d=st==='full'?1:-1;S.update(s=>{const u=s.classes.treasureHunter.featureUses||(s.classes.treasureHunter.featureUses={});u[id]=Math.max(0,Math.min(max,(Number(u[id])||0)+d))});S.flush();render()}
  function relicUse(i,st){const d=st==='full'?1:-1;S.update(s=>{let x=s.classes.treasureHunter.relics[i];if(typeof x==='string'){x={id:x,prepared:false,used:0};s.classes.treasureHunter.relics[i]=x}if(!x)return;const r={...((T.relics||[]).find(y=>y.id===x.id)||{}),...x},max=relicMax(r);x.used=Math.max(0,Math.min(max,(Number(x.used)||0)+d))});S.flush();render()}
  document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.actionsFilter){e.preventDefault();e.stopImmediatePropagation();S.update(s=>s.ui.actionFilter=t.dataset.actionsFilter);S.flush();render()}else if(t.dataset.actionsFav){e.preventDefault();e.stopImmediatePropagation();S.update(s=>{const a=s.ui.favoriteActions||(s.ui.favoriteActions=[]),i=a.indexOf(t.dataset.actionsFav);i>=0?a.splice(i,1):a.push(t.dataset.actionsFav)});S.flush();render()}else if(t.dataset.actionsOpen){e.preventDefault();e.stopImmediatePropagation();open.has(t.dataset.actionsOpen)?open.delete(t.dataset.actionsOpen):open.add(t.dataset.actionsOpen);render()}else if(t.dataset.actionsFeature){e.preventDefault();e.stopImmediatePropagation();featureUse(t.dataset.actionsFeature,t.dataset.chargeState)}else if(t.dataset.actionsRelic!=null){e.preventDefault();e.stopImmediatePropagation();relicUse(Number(t.dataset.actionsRelic),t.dataset.chargeState)}else if(t.dataset.actionsCool){e.preventDefault();e.stopImmediatePropagation();const cost=Number(t.dataset.actionsCool),total=T.coolTotal(level()),used=Number(state().classes.treasureHunter.coolUsed)||0;if(total-used<cost)return;S.update(s=>s.classes.treasureHunter.coolUsed=Math.min(total,used+cost));S.flush();render()}else if(t.dataset.actionsDelete){e.preventDefault();e.stopImmediatePropagation();S.update(s=>s.character.customActions=s.character.customActions.filter(a=>a.id!==t.dataset.actionsDelete));S.flush();render()}},true);
  document.addEventListener('change',e=>{if(e.target.dataset.actionsSort){S.update(s=>s.ui.actionSort=e.target.value);S.flush();render()}},true);
  document.addEventListener('DOMContentLoaded',render);S.subscribe(()=>requestAnimationFrame(render));window.V7SActionsRender=render;
})();