(function(){
  const S=window.V7SStateV7s,T=window.TreasureHunterDataV7s,R=window.DND2024Rules;
  T.relics=window.TreasureHunterRelicsV7s||[];
  const PAGES=['character','actions','skills','features','relics','gear','npcs'];
  const TITLES=['CHARACTER','ACTIONS','SKILLS','FEATURES','RELICS','GEAR','NPCs'];
  const ALL_SKILLS={Acrobatics:'DEX','Animal Handling':'WIS',Arcana:'INT',Athletics:'STR',Deception:'CHA',History:'INT',Insight:'WIS',Intimidation:'CHA',Investigation:'INT',Medicine:'WIS',Nature:'INT',Perception:'WIS',Performance:'CHA',Persuasion:'CHA',Religion:'INT','Sleight of Hand':'DEX',Stealth:'DEX',Survival:'WIS'};
  const DEFENSE_ARRAY={resistance:'resistances',immunity:'immunities',vulnerability:'vulnerabilities',conditionImmunity:'conditionImmunities'};
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const signed=S.signed,mod=S.modifier;
  let actionFilter='all',featureSearch='',featureFilter='all',hpAmount=1,raf=0,savePageTimer=0,shortRestDice=0,activeDetailKey='';

  const state=()=>S.get();
  const level=()=>Math.max(1,Math.min(20,Number(state().character.level)||1));
  const pb=()=>T.pb(level());
  const coolTotal=()=>T.coolTotal(level());
  const coolUsed=()=>Math.max(0,Math.min(coolTotal(),Number(state().classes.treasureHunter.coolUsed)||0));
  const coolAvailable=()=>Math.max(0,coolTotal()-coolUsed());
  const coolDie=()=>T.coolDie(level());
  const ability=a=>Number(state().character.abilities[a])||10;
  const abilityMod=a=>mod(ability(a));
  const conditions=()=>Array.isArray(state().character.conditions)?state().character.conditions:[];
  const exhaustion=()=>Math.max(0,Math.min(6,Number(state().character.exhaustion)||0));
  const d20Penalty=()=>R.exhaustionPenalty(exhaustion());
  const saveAutoFails=a=>R.saveAutoFails(conditions(),a)||exhaustion()>=6;
  const saveMod=a=>saveAutoFails(a)?null:abilityMod(a)+(T.saves.includes(a)?pb():0)+d20Penalty();
  const initiative=()=>abilityMod('DEX')+(Number(state().character.initiativeBonus)||0)+d20Penalty();
  const relicDC=()=>8+pb()+abilityMod('INT');
  const whipDC=()=>8+pb()+abilityMod('DEX');
  const relicLimit=()=>T.relicLimit(level());
  const cannotAct=()=>exhaustion()>=6||R.isIncapacitated(conditions());
  const hitDiceSpent=()=>Math.max(0,Math.min(level(),Number(state().character.hitDice?.d10?.spent)||0));
  const hitDiceAvailable=()=>Math.max(0,level()-hitDiceSpent());

  function selectedRelics(){return (state().classes.treasureHunter.relics||[]).map(r=>typeof r==='string'?{id:r,prepared:false,used:0}:{prepared:false,used:0,...r})}
  function relicById(id){return T.relics.find(r=>r.id===id)}
  function activeRelics(){return selectedRelics().filter(r=>r.prepared).map(r=>({...relicById(r.id),...r})).filter(Boolean)}
  function relicSpeedBonus(){return activeRelics().reduce((n,r)=>n+(Number(r.bonusSpeed)||0),0)}
  function derivedSpeed(){if(exhaustion()>=6||R.speedIsZero(conditions()))return 0;return Math.max(0,(Number(state().character.speed)||0)+relicSpeedBonus()-R.exhaustionSpeedPenalty(exhaustion()))}
  function derivedSenses(){const out=[...(state().character.proficiencies.senses||[])];activeRelics().forEach(r=>{if(r.truesight)out.push(`Pravé vidění ${r.truesight} ft`);if(r.darkvision)out.push(`Temnovid +${r.darkvision} ft`)});return [...new Set(out)]}
  function conditionImmunities(){const out=[...(state().character.damageDefenses?.conditionImmunities||[])];if(activeRelics().some(r=>r.id==='last-exorcists-testament'))out.push('Charmed','Frightened');if(conditions().includes('Petrified'))out.push('Poisoned');return [...new Set(out)]}
  function derivedDefenseText(){const out=[...(state().character.proficiencies.defenses||[])];const d=state().character.damageDefenses||{};(d.resistances||[]).forEach(x=>out.push(`Odolnost: ${R.damageTypeName(x)}`));(d.immunities||[]).forEach(x=>out.push(`Imunita: ${R.damageTypeName(x)}`));(d.vulnerabilities||[]).forEach(x=>out.push(`Zranitelnost: ${R.damageTypeName(x)}`));conditionImmunities().forEach(x=>out.push(`Imunita vůči stavu: ${R.conditionName(x)}`));if(activeRelics().some(r=>r.id==='cloak-pilgrim-worlds'))out.push('Odolnost: typ zvolený Pláštěm poutníka mezi světy');if(conditions().includes('Petrified'))out.push('Odolnost vůči všemu zranění (Zkamenělý)');return [...new Set(out)]}
  function pageIntro(title,subtitle){return `<div class="page-intro"><span>${esc(title)}</span><small>${esc(subtitle)}</small></div>`}
  function stat(label,value,cls='',attrs=''){return `<button class="stat ${cls}" ${attrs}><span>${esc(label)}</span><b>${esc(value)}</b></button>`}
  function section(title,body,right=''){return `<section class="section"><div class="section-head"><h2>${title}</h2>${right}</div>${body}</section>`}
  function actionCode(a){if(a==='Action')return'A';if(a==='Bonus Action')return'BA';if(a==='Reaction')return'R';if(a==='Free')return'FREE';if(a==='Special')return'SA';return a==='Resource'?'RES':'PASS'}
  function badgeClass(a){const c=actionCode(a);return c==='A'?'a':c==='BA'?'ba':c==='R'?'r':'pass'}
  function rowCard(id,title,meta,detail,action='Passive',extra=''){return `<article class="row-card" data-row="${esc(id)}"><button class="row-main" data-toggle-row="${esc(id)}"><span><strong>${esc(title)}</strong><span class="row-meta">${meta}</span></span><span class="badge ${badgeClass(action)}">${esc(actionCode(action))}</span></button><div class="row-detail">${detail}${extra}</div></article>`}
  function toast(message,type='success'){const host=$('#toastHost');if(!host)return;const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;host.appendChild(el);setTimeout(()=>{el.style.opacity='0';el.style.transform='translateY(6px)';setTimeout(()=>el.remove(),180)},2100)}

  function statusBanner(){
    const tags=[];let strong='',text='';
    if(exhaustion()>=6){strong='Vyčerpání 6';text='Podle pravidel D&D 2024 je postava mrtvá.';tags.push('D20 Testy −12','Rychlost 0')}
    else if(exhaustion()>0){strong=`Vyčerpání ${exhaustion()}`;text=`Každý D20 Test má ${d20Penalty()} a Rychlost je snížena o ${R.exhaustionSpeedPenalty(exhaustion())} ft.`;tags.push(`D20 ${d20Penalty()}`,`Speed −${R.exhaustionSpeedPenalty(exhaustion())} ft`)}
    if(R.isIncapacitated(conditions()))tags.push('Vyřazený: bez A / BA / R');
    if(R.speedIsZero(conditions()))tags.push('Rychlost 0');
    const dis=R.attackDisadvantage(conditions());if(dis.length)tags.push(`Útoky: Nevýhoda (${dis.map(R.conditionName).join(', ')})`);
    if(conditions().includes('Restrained'))tags.push('DEX save: Nevýhoda');
    if(conditions().includes('Frightened'))tags.push('Vystrašený: podmíněná Nevýhoda');
    if(!strong&&tags.length){strong='Aktivní stavy';text='Některé stavy mění dostupné akce nebo způsob hodů.'}
    return tags.length||strong?`<div class="status-banner"><strong>${esc(strong)}</strong>${text?` ${esc(text)}`:''}<div class="status-tags">${tags.map(t=>`<span class="status-tag ${/0|mrtvá|bez/.test(t)?'danger':'warn'}">${esc(t)}</span>`).join('')}</div></div>`:'';
  }

  function conditionOptions(){const active=new Set(conditions()),immune=new Set(conditionImmunities());return Object.entries(R.CONDITIONS).filter(([k])=>!active.has(k)&&!immune.has(k)).map(([k,v])=>`<option value="${k}">${esc(v.name)}</option>`).join('')}
  function conditionChips(){const chips=conditions().map(k=>{const info=R.CONDITIONS[k];return `<span class="condition-detail-btn ${['Paralyzed','Petrified','Stunned','Unconscious','Incapacitated'].includes(k)?'active-danger':''}" data-detail="condition:${k}">${esc(info?.name||k)} <button data-remove-condition="${esc(k)}" aria-label="Odebrat">×</button></span>`}).join('');const ex=exhaustion()>0?`<span class="condition-detail-btn exhaustion" data-detail="exhaustion">Vyčerpání ${exhaustion()}</span>`:'';return chips+ex||'<span class="muted">Žádné aktivní stavy</span>'}

  function defenseChips(){
    const d=state().character.damageDefenses||{};let out='';
    Object.entries(DEFENSE_ARRAY).forEach(([type,key])=>(d[key]||[]).forEach((v,i)=>{const label=type==='conditionImmunity'?R.conditionName(v):R.damageTypeName(v);out+=`<span class="defense-chip ${type}">${esc(R.DEFENSE_TYPES[type])}: ${esc(label)} <button data-remove-defense="${type}:${i}" aria-label="Odebrat">×</button></span>`}));
    if(activeRelics().some(r=>r.id==='last-exorcists-testament'))out+=`<span class="defense-chip conditionImmunity">Relikvie: Okouzlený, Vystrašený</span>`;
    if(activeRelics().some(r=>r.id==='cloak-pilgrim-worlds'))out+=`<span class="defense-chip resistance">Relikvie: zvolená Odolnost</span>`;
    return out||'<span class="muted">Žádné obrany ani zranitelnosti</span>';
  }
  function defenseValueOptions(type){if(type==='conditionImmunity')return Object.entries(R.CONDITIONS).map(([k,v])=>`<option value="${k}">${esc(v.name)}</option>`).join('');return R.DAMAGE_TYPES.map(([k,n])=>`<option value="${k}">${esc(n)}</option>`).join('')}

  function renderTop(){const s=state();$('#topName').textContent=s.character.name||'Nová postava';$('#topClass').textContent=`Treasure Hunter ${level()} • PB ${signed(pb())}`;$('#hudHp').textContent=`${s.character.hp.current}/${s.character.hp.max}`;$('#hudAc').textContent=s.character.ac;$('#hudCool').textContent=level()>=2?`${coolAvailable()}/${coolTotal()} ${coolDie()}`:`— ${coolDie()}`}

  function renderCharacter(){
    const s=state(),hp=s.character.hp;
    const portrait=s.character.portrait?`<img class="hero-portrait" src="${s.character.portrait}" alt="Portrét postavy">`:`<button class="hero-portrait placeholder" data-open-edit aria-label="Přidat portrét">＋</button>`;
    const abilities=S.A.map(a=>{const sv=saveMod(a),auto=saveAutoFails(a);return `<button class="ability" data-detail="ability:${a}"><div class="abbr">${a}</div><div class="mod">${signed(abilityMod(a))}</div><div class="score">${ability(a)}</div><div class="save ${T.saves.includes(a)?'prof':''}">${auto?'<span class="save-state">AUTO FAIL</span>':`${T.saves.includes(a)?'●':'○'} ${signed(sv)}`}</div></button>`}).join('');
    let dots='';for(let i=0;i<coolTotal();i++)dots+=`<button class="cool-dot ${i<coolAvailable()?'filled':''}" data-cool-set="${i+1}" aria-label="Nastavit dostupné Cool Points na ${i+1}"></button>`;
    const sense=[...derivedSenses(),...derivedDefenseText()];
    const condManager=`<div class="condition-manager"><div class="exhaustion-row"><div class="exhaustion-copy"><b>Vyčerpání</b><small>D&D 2024: −2 na D20 Testy a −5 ft Rychlosti za úroveň.</small></div><div class="exhaustion-controls"><button data-exhaustion="-1">−</button><strong>${exhaustion()}</strong><button data-exhaustion="1">+</button></div></div><div class="condition-strip">${conditionChips()}</div><div class="manager-row"><select id="conditionSelect"><option value="">Přidat stav…</option>${conditionOptions()}</select><button data-add-condition>+</button></div></div>`;
    const defenseManager=`<div class="defense-manager"><div class="condition-strip">${defenseChips()}</div><div class="manager-row two-select"><select id="defenseType"><option value="resistance">Odolnost</option><option value="immunity">Imunita</option><option value="vulnerability">Zranitelnost</option><option value="conditionImmunity">Imunita vůči stavu</option></select><select id="defenseValue">${defenseValueOptions('resistance')}</select><button data-add-defense>+</button></div></div>`;
    $('#characterPage').innerHTML=`${pageIntro('CHARACTER','Přehled postavy')}${statusBanner()}
      ${section('',`<div class="character-hero">${portrait}<div class="hero-copy"><span class="eyebrow">TREASURE HUNTER ${level()}</span><h1>${esc(s.character.name||'Nová postava')}</h1><p>${esc(s.character.race||'')}</p></div></div><div class="stat-grid hero-stats">${stat('HP',`${hp.current}/${hp.max}`,'hp-stat','data-open-hp')}${stat('AC',s.character.ac,'','data-detail="ac"')}${stat('INIT',signed(initiative()),'','data-detail="initiative"')}${stat('SPEED',`${derivedSpeed()} ft`,'','data-detail="speed"')}</div><div class="hero-actions"><button class="small-btn ${s.character.inspiration?'primary':''}" data-inspiration>✦ Inspirace</button><button class="small-btn" data-short-rest>Krátký odpočinek</button><button class="small-btn" data-long-rest>Dlouhý odpočinek</button></div>`)}
      ${section('Cool',level()<2?`<div class="resource-row"><button class="small-btn" data-detail="cool">${coolDie()}</button><span class="muted">Cool Points získáš na 2. úrovni.</span></div>`:`<div class="resource-row"><div><button class="small-btn" data-detail="cool"><span class="eyebrow">COOL POINTS • ${coolAvailable()} / ${coolTotal()} • ${coolDie()}</span></button><div class="cool-dots">${dots}</div></div><div class="tiny-controls"><button data-cool="-1">+</button><button data-cool="1">−</button></div></div>`)}
      ${section('Vlastnosti & záchranné hody',`<div class="ability-grid">${abilities}</div>`)}
      ${section('Class DC',`<div class="stat-grid">${stat('WHIP DC',whipDC(),'compact','data-detail="whipDC"')}${stat('ROPE DC',whipDC(),'compact','data-detail="ropeDC"')}${stat('RELIC DC',relicDC(),'compact','data-detail="relicDC"')}${stat('PB',signed(pb()),'compact','data-detail="pb"')}</div>`)}
      ${sense.length?section('Smysly & obrany',`<div class="condition-strip">${sense.map(x=>`<span class="chip brass">${esc(x)}</span>`).join('')}</div>`):''}
      ${section('Stavy',condManager)}
      ${section('Odolnosti, imunity & zranitelnosti',defenseManager)}`;
  }

  function allActions(){const out=[];T.features.filter(f=>f.level<=level()).forEach(f=>{if(f.action&&!['Passive','Resource'].includes(f.action))out.push({id:f.id,name:f.name,action:f.action,summary:f.summary,cost:f.cost||0,source:f.name,uses:f.uses,recovery:f.recovery});(f.actions||[]).forEach(a=>out.push({...a,source:f.name,level:f.level}))});return out}
  function actionMatch(a){if(actionFilter==='all')return true;const c=actionCode(a.action).toLowerCase();if(actionFilter==='a')return c==='a';if(actionFilter==='ba')return c==='ba';if(actionFilter==='r')return c==='r';return actionFilter==='special'?['sa','free'].includes(c):true}
  function featureUsesLeft(f){if(!f.uses)return null;const used=Number(state().classes.treasureHunter.featureUses?.[f.id])||0;return Math.max(0,f.uses-used)}
  function featureById(id){return T.features.find(f=>f.id===id)}
  function actionSourceFeature(a){return T.features.find(f=>f.name===a.source)||featureById(a.id)}
  function attackContext(){const notes=[];const dis=R.attackDisadvantage(conditions());if(dis.length)notes.push(`Nevýhoda: ${dis.map(R.conditionName).join(', ')}`);if(conditions().includes('Frightened'))notes.push('Vystrašený: Nevýhoda pokud vidíš zdroj strachu');if(conditions().includes('Grappled'))notes.push('Chycený: Nevýhoda proti jinému cíli než grapplerovi');if(exhaustion())notes.push(`Vyčerpání: ${d20Penalty()} k hodu`);return notes.join(' • ')}
  function weaponRows(){return (state().character.gear.weapons||[]).map(w=>{const a=w.attackAbility||'DEX',atk=abilityMod(a)+pb()+d20Penalty(),ctx=attackContext();return rowCard(`weapon-${w.id}`,w.name,`<span>${signed(atk)} k zásahu</span><span>${esc(w.damage)} + ${signed(abilityMod(a))}</span>`,`Bonus k útoku: ${signed(atk)}\n${a} ${signed(abilityMod(a))} + PB ${signed(pb())}${exhaustion()?` + Vyčerpání ${d20Penalty()}`:''}\nZranění: ${esc(w.damage)} + ${signed(abilityMod(a))} ${esc(w.damageType||'')}${ctx?`<div class="attack-context">${esc(ctx)}</div>`:''}`,'Action')}).join('')||'<div class="empty">Žádné zbraně.</div>'}
  function renderActions(){
    const filters=[['all','ALL'],['a','A'],['ba','BA'],['r','R'],['special','SPECIAL']].map(([k,l])=>`<button class="filter-btn ${actionFilter===k?'active':''}" data-action-filter="${k}">${l}</button>`).join('');
    const rows=allActions().filter(actionMatch).map(a=>{const f=actionSourceFeature(a),left=f?featureUsesLeft(f):null,meta=`<span>${esc(a.source||'Treasure Hunter')}</span>${a.cost?`<span>${a.cost} Cool</span>`:''}${left!=null?`<span>${left}/${f.uses}</span>`:''}`;let controls='';if(a.cost)controls+=`<button class="small-btn primary" data-use-action="${esc(a.id)}" ${cannotAct()?'disabled':''}>Použít • −${a.cost} Cool</button>`;if(left!=null)controls+=`<button class="small-btn primary" data-use-feature="${esc(f.id)}" ${(left<=0||cannotAct())?'disabled':''}>Použít • ${left}/${f.uses}</button>`;return rowCard(a.id,a.name,meta,esc(a.summary),a.action,controls?`<div class="detail-actions">${controls}</div>`:'')}).join('')||'<div class="empty">Pro tento filtr nejsou žádné akce.</div>';
    const relicActions=activeRelics().filter(r=>r.action!=='Passive').map(r=>rowCard(`relic-${r.id}`,r.name,`<span>RELIKVIE</span>${r.charges?`<span>${Math.max(0,r.charges-(r.used||0))}/${r.charges}</span>`:''}`,esc(r.summary),r.action)).join('');
    $('#actionsPage').innerHTML=`${pageIntro('ACTIONS','Boj a aktivní schopnosti')}${cannotAct()?'<div class="status-banner"><strong>Vyřazený stav.</strong> Aktivní bojové schopnosti jsou dočasně zamčené.</div>':''}${section('Filtr',`<div class="filters">${filters}</div>`)}${section('Útoky',`<div class="list">${weaponRows()}</div>`)}${section('Treasure Hunter',`<div class="list">${rows}</div>`)}${relicActions?section('Připravené relikvie',`<div class="list">${relicActions}</div>`):''}`;
  }

  function skillStatus(n){return Math.max(0,Math.min(2,Number(state().character.skills?.[n])||0))}
  function skillMod(n){const st=skillStatus(n),a=ALL_SKILLS[n];return abilityMod(a)+(st?pb()*st:0)+d20Penalty()}
  function renderSkills(){
    const rows=Object.keys(ALL_SKILLS).map(n=>{const st=skillStatus(n),cls=st===2?'expert':st===1?'prof':'',pen=exhaustion()?'penalized':'';return `<div class="skill-row clickable" data-detail="skill:${encodeURIComponent(n)}"><button class="prof-dot ${cls}" data-skill-cycle="${esc(n)}">${st===2?'◆':st===1?'●':'○'}</button><span class="skill-name">${esc(n)}</span><span class="skill-ability">${ALL_SKILLS[n]}</span><span class="skill-mod ${pen}">${signed(skillMod(n))}</span></div>`}).join('');
    const p=state().character.proficiencies,th=state().classes.treasureHunter;const details=(t,b)=>`<details class="proficiency"><summary>${t}</summary><div class="prof-body">${esc(b||'—')}</div></details>`;const langs=[...(p.languages||[]),...(th.ancientLanguages||[]).filter(Boolean)],veh=[...(p.vehicles||[]),...(th.vehicles||[]).filter(Boolean)];
    $('#skillsPage').innerHTML=`${pageIntro('SKILLS','Skills & Proficiencies')}${exhaustion()?`<div class="status-banner"><strong>Vyčerpání ${exhaustion()}.</strong> Zobrazené bonusy ke skillům už obsahují ${d20Penalty()} k D20 Testu.</div>`:''}${section('Skills',`<div>${rows}</div>`)}${section('Proficiencies',`${details('Armor',[...new Set([...T.armor,...(p.armor||[])])].join(' • '))}${details('Weapons',[...new Set([...T.weapons,...(p.weapons||[])])].join(' • '))}${details('Tools',[...new Set([...(p.tools||[])])].join(' • '))}${details('Vehicles',[...new Set(veh)].join(' • '))}${details('Languages',[...new Set(langs)].join(' • '))}${details('Senses & Defenses',[...derivedSenses(),...derivedDefenseText()].join(' • '))}`)}`;
  }

  function featureMatch(f){const q=featureSearch.trim().toLowerCase();if(q&&!`${f.name} ${f.summary}`.toLowerCase().includes(q))return false;if(featureFilter==='all')return true;if(featureFilter==='active')return f.action!=='Passive'||(f.actions||[]).length;if(featureFilter==='passive')return f.action==='Passive'&&!(f.actions||[]).length;if(featureFilter==='subclass')return f.kind==='subclass';return actionCode(f.action).toLowerCase()===featureFilter}
  function renderFeatures(){
    const fav=state().ui.favoriteFeatures||[];const rows=T.features.filter(f=>f.level<=level()).filter(featureMatch).sort((a,b)=>(fav.includes(a.id)?0:1)-(fav.includes(b.id)?0:1)||a.level-b.level||a.name.localeCompare(b.name)).map(f=>{const left=featureUsesLeft(f),sub=(f.actions||[]).map(a=>`<div class="subaction"><b>${esc(a.name)}</b><span>${esc(actionCode(a.action))}</span><p>${esc(a.summary)}</p></div>`).join('');return rowCard(f.id,f.name,`<span>Úroveň ${f.level}</span>${f.kind==='subclass'?'<span>Okultní sběratel</span>':''}${left!=null?`<span>${left}/${f.uses}</span>`:''}`,`${esc(f.summary)}${sub?`<div class="subactions">${sub}</div>`:''}`,f.action,`<div class="detail-actions"><button class="favorite ${fav.includes(f.id)?'on':''}" data-favorite="${f.id}">★</button>${f.cost?`<button class="small-btn primary" data-use-action="${f.id}" ${cannotAct()?'disabled':''}>Použít • −${f.cost} Cool</button>`:''}${left!=null?`<button class="small-btn primary" data-use-feature="${f.id}" ${(left<=0||cannotAct())?'disabled':''}>Použít • ${left}/${f.uses}</button>`:''}</div>`)}).join('')||'<div class="empty">Nic nenalezeno.</div>';
    const filters=[['all','ALL'],['active','ACTIVE'],['passive','PASSIVE'],['subclass','SUBCLASS']].map(([k,l])=>`<button class="filter-btn ${featureFilter===k?'active':''}" data-feature-filter="${k}">${l}</button>`).join('');
    $('#featuresPage').innerHTML=`${pageIntro('FEATURES','Class & Subclass Features')}${section('Najít feature',`<input id="featureSearch" class="search-inline" value="${esc(featureSearch)}" placeholder="Hledat feature…"><div class="filters top-gap">${filters}</div>`)}${section('Features',`<div class="list">${rows}</div>`,`<span class="eyebrow">LEVEL ${level()}</span>`)}`;
  }

  function renderRelics(){
    const lim=relicLimit(),sel=selectedRelics(),prep=sel.filter(r=>r.prepared).length,reserve=sel.length-prep,available=T.relics.filter(r=>r.level<=level()&&!sel.some(x=>x.id===r.id));
    const cards=sel.map((x,i)=>{const r={...relicById(x.id),...x},charges=r.charges||0,used=Math.min(charges,Number(r.used)||0),left=Math.max(0,charges-used);return `<article class="relic-card ${r.prepared?'prepared':''}"><div class="relic-top"><div><div class="eyebrow">${r.prepared?'PŘIPRAVENÁ':'ZÁLOHA'} • LVL ${r.level}</div><h3>${esc(r.name)}</h3></div><button class="small-btn" data-relic-remove="${i}">×</button></div><p>${esc(r.summary)}</p>${charges?`<div class="charge-row"><span>${left}/${charges} nábojů</span><div>${Array.from({length:charges},(_,n)=>`<button class="charge-dot ${n<left?'filled':''}" data-relic-use="${i}" aria-label="Spotřebovat náboj"></button>`).join('')}</div></div>`:''}<div class="detail-actions"><button class="small-btn ${r.prepared?'primary':''}" data-relic-prepared="${i}">${r.prepared?'Připravená':'Připravit'}</button>${charges&&used?`<button class="small-btn" data-relic-refill="${i}">Obnovit</button>`:''}</div></article>`}).join('')||'<div class="empty">Zatím nemáš žádné relikvie.</div>';
    const options=available.map(r=>`<option value="${r.id}">${esc(r.name)} • lvl ${r.level}</option>`).join('');
    $('#relicsPage').innerHTML=`${pageIntro('RELICS','Okultní sběratel')}${section('Kapacita',`<div class="stat-grid">${stat('PŘIPR.',`${prep}/${lim[0]}`,'compact')}${stat('ZÁLOHA',`${reserve}/${lim[1]}`,'compact')}${stat('CELKEM',`${sel.length}/${lim[2]}`,'compact')}${stat('RELIC DC',relicDC(),'compact','data-detail="relicDC"')}</div>`)}${section('Sbírka',`<div class="inline-form"><select id="relicSelect" class="search-inline" ${sel.length>=lim[2]?'disabled':''}><option value="">Přidat relikvii…</option>${options}</select><button class="small-btn" data-add-relic ${sel.length>=lim[2]?'disabled':''}>+</button></div><div class="relic-grid top-gap">${cards}</div>`)}`;
  }

  function renderGear(){const g=state().character.gear,m=g.money||{};const money=['cp','sp','gp','pp'].map(k=>`<label>${k.toUpperCase()}<input type="number" min="0" value="${Number(m[k])||0}" data-money="${k}"></label>`).join('');const weapons=(g.weapons||[]).map((w,i)=>`<article class="gear-card"><div class="gear-top"><h3>${esc(w.name)}</h3><button class="small-btn" data-weapon-remove="${i}">×</button></div><div class="muted">${esc(w.damage)} ${esc(w.damageType||'')} • ${esc(w.mastery||'')}</div></article>`).join('')||'<div class="empty">Žádné zbraně.</div>';const items=(g.inventory||[]).map((it,i)=>`<article class="gear-card"><div class="gear-top"><h3>${esc(typeof it==='string'?it:it.name||'Předmět')}</h3><button class="small-btn" data-item-remove="${i}">×</button></div></article>`).join('')||'<div class="empty">Inventář je prázdný.</div>';$('#gearPage').innerHTML=`${pageIntro('GEAR','Výbava a inventář')}${section('Peníze',`<div class="money-grid">${money}</div>`)}${section('Zbraně',`<div class="gear-grid">${weapons}</div>`)}${section('Inventář',`<div class="inline-form"><input id="newItemName" class="search-inline" placeholder="Přidat předmět"><button class="small-btn" data-add-item>+</button></div><div class="gear-grid top-gap">${items}</div>`)}`}
  function renderNpcs(){const npcs=state().campaign.npcs||[];const cards=npcs.map((n,i)=>`<article class="npc-card" data-edit-npc="${i}">${n.image?`<img class="npc-photo" src="${n.image}" alt="">`:`<div class="npc-photo npc-placeholder">♟</div>`}<div class="npc-info"><div class="npc-top"><div><div class="eyebrow">${esc(n.tag||'NPC')}${n.location?` • ${esc(n.location)}`:''}</div><h3>${esc(n.name||'NPC')}</h3></div><button class="favorite ${n.favorite?'on':''}" data-npc-favorite="${i}">★</button></div><p>${esc(n.notes||'')}</p></div></article>`).join('')||'<div class="empty">Žádná NPC.</div>';$('#npcsPage').innerHTML=`${pageIntro('NPCs','Kartotéka postav')}${section('NPCs',`<button class="small-btn primary" data-new-npc>+ NPC</button>`)}${section('Kartotéka',`<div class="npc-grid">${cards}</div>`)}`}
  function renderAll(){renderTop();renderCharacter();renderActions();renderSkills();renderFeatures();renderRelics();renderGear();renderNpcs();updatePageChrome()}

  function currentPageIndex(){const p=$('#pager');return Math.max(0,Math.min(PAGES.length-1,Math.round(p.scrollLeft/Math.max(1,p.clientWidth))))}
  function updatePageChrome(i=currentPageIndex()){$('#pageTitle').textContent=TITLES[i];$$('#pageDots .page-dot').forEach((d,j)=>d.classList.toggle('active',i===j))}
  function setPage(i,smooth=true){i=Math.max(0,Math.min(PAGES.length-1,i));const p=$('#pager');p.scrollTo({left:p.clientWidth*i,behavior:smooth?'smooth':'auto'});updatePageChrome(i);S.update(s=>s.ui.page=i)}
  function initDots(){$('#pageDots').innerHTML=PAGES.map((p,i)=>`<button class="page-dot" data-page-dot="${i}" aria-label="${TITLES[i]}"></button>`).join('')}
  function onPagerScroll(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const i=currentPageIndex();updatePageChrome(i);clearTimeout(savePageTimer);savePageTimer=setTimeout(()=>S.update(s=>s.ui.page=i),80)})}

  function spendCool(cost){cost=Number(cost)||0;if(cost<=0)return true;if(coolAvailable()<cost){toast('Nemáš dost Cool Points.','warn');return false}S.update(s=>s.classes.treasureHunter.coolUsed=Math.min(coolTotal(),(Number(s.classes.treasureHunter.coolUsed)||0)+cost));toast(`Spotřebováno ${cost} Cool Point${cost===1?'':'s'}.`);return true}
  function useFeature(id){const f=featureById(id);if(!f||!f.uses)return;const left=featureUsesLeft(f);if(left<=0){toast('Tato schopnost už nemá použití.','warn');return}S.update(s=>{s.classes.treasureHunter.featureUses||(s.classes.treasureHunter.featureUses={});s.classes.treasureHunter.featureUses[id]=(Number(s.classes.treasureHunter.featureUses[id])||0)+1});toast(`${f.name}: použito.`);renderAll()}
  function resetFeatures(s,kind){Object.keys(s.classes.treasureHunter.featureUses||{}).forEach(id=>{const f=featureById(id);if(f&&(kind==='LR'||f.recovery==='SR'||f.recovery==='LR'))s.classes.treasureHunter.featureUses[id]=0})}
  function resetRelics(s,kind){(s.classes.treasureHunter.relics||[]).forEach(x=>{if(typeof x==='string')return;const r=relicById(x.id);if(r&&(kind==='LR'||r.recovery==='SR'))x.used=0})}

  function damageAdjustment(amount,type){let n=Math.max(0,Number(amount)||0);const d=state().character.damageDefenses||{},notes=[];if(!type)return{amount:n,notes};if((d.immunities||[]).includes(type)){notes.push(`Imunita vůči ${R.damageTypeName(type)}mu zranění`);return{amount:0,notes}}const resist=(d.resistances||[]).includes(type)||conditions().includes('Petrified'),vuln=(d.vulnerabilities||[]).includes(type);if(resist){n=Math.floor(n/2);notes.push('Odolnost: × 1/2')}if(vuln){n=n*2;notes.push('Zranitelnost: × 2')}return{amount:n,notes}}
  function updateHpDamageNote(){const type=$('#hpDamageType')?.value||'',adj=damageAdjustment(hpAmount,type),el=$('#hpDamageNote');if(!el)return;el.innerHTML=type?`${esc(R.damageTypeName(type))}: <strong>${hpAmount} → ${adj.amount}</strong>${adj.notes.length?` • ${esc(adj.notes.join(' • '))}`:''}`:'Zadej zranění; volitelný typ automaticky použije Odolnost, Imunitu nebo Zranitelnost.'}
  function openHp(){const h=state().character.hp;hpAmount=1;$('#hpCurrent').textContent=h.current;$('#hpMax').textContent=h.max;$('#hpTemp').value=h.temp||0;$('#hpTempRead').textContent=h.temp||0;$('#hpAmount').textContent=hpAmount;$('#hpDamageType').innerHTML='<option value="">Bez typu / neuplatňovat obrany</option>'+R.DAMAGE_TYPES.map(([k,n])=>`<option value="${k}">${esc(n)}</option>`).join('');updateHpDamageNote();$('#hpDialog').showModal()}
  function updateHpAmount(delta){hpAmount=Math.max(1,Math.min(999,hpAmount+delta));$('#hpAmount').textContent=hpAmount;updateHpDamageNote()}
  function applyHp(mode){let applied=hpAmount,type=$('#hpDamageType').value||'';if(mode==='damage')applied=damageAdjustment(hpAmount,type).amount;S.update(s=>{const h=s.character.hp;if(mode==='damage'){let dmg=applied,absorb=Math.min(h.temp||0,dmg);h.temp=(h.temp||0)-absorb;dmg-=absorb;h.current=Math.max(0,h.current-dmg)}else h.current=Math.min(h.max,h.current+hpAmount);h.temp=Math.max(0,Number($('#hpTemp').value)||0)});$('#hpDialog').close();toast(mode==='damage'?`Zranění: ${applied} HP.`:`Léčení: ${hpAmount} HP.`,mode==='damage'?'danger':'success');renderAll()}

  function restSummaryHtml(){const h=state().character.hp;return `<div class="rest-summary"><div class="rest-stat"><span>HP</span><b>${h.current}/${h.max}</b></div><div class="rest-stat"><span>HIT DICE</span><b>${hitDiceAvailable()}/${level()} d10</b></div><div class="rest-stat"><span>COOL</span><b>${coolAvailable()}/${coolTotal()}</b></div><div class="rest-stat"><span>VYČERPÁNÍ</span><b>${exhaustion()}</b></div></div>`}
  function shortResourceText(){const usedFeatures=T.features.filter(f=>f.recovery==='SR'&&(Number(state().classes.treasureHunter.featureUses?.[f.id])||0)>0).map(f=>f.name);const usedRelics=selectedRelics().map(x=>({...relicById(x.id),...x})).filter(r=>r.recovery==='SR'&&(Number(r.used)||0)>0).map(r=>r.name);return{features:usedFeatures,relics:usedRelics}}
  function renderShortRestBody(){const h=state().character.hp,res=shortResourceText(),can=h.current>0,preview=Math.min(h.max,h.current+shortRestDice*Math.max(1,6+abilityMod('CON')));$('#shortRestBody').innerHTML=`${!can?'<div class="rest-warning">Krátký odpočinek můžeš podle D&D 2024 zahájit jen s alespoň 1 HP.</div>':''}${restSummaryHtml()}<div class="rest-card"><div class="rest-card-head"><h3>Hit Dice</h3><button type="button" class="small-btn" data-detail="hitDice">Jak se počítají?</button></div><p>Treasure Hunter používá d10. Vyber, kolik kostek chceš utratit. Při dokončení se každá hodí a přičte se modifikátor Odolnosti.</p><div class="hit-die-picker"><button type="button" data-short-dice="-1" ${shortRestDice<=0?'disabled':''}>−</button><div class="hit-die-center"><strong>${shortRestDice}d10</strong><small>dostupné ${hitDiceAvailable()} • CON ${signed(abilityMod('CON'))}</small></div><button type="button" data-short-dice="1" ${shortRestDice>=hitDiceAvailable()?'disabled':''}>+</button></div>${shortRestDice?`<div class="calculation-note">Očekávané léčení je přibližně ${Math.max(1,shortRestDice*(5.5+abilityMod('CON'))).toFixed(1)} HP; skutečný výsledek se hodí při dokončení.</div>`:''}</div><div class="rest-card"><h3>Co obnovit</h3><div class="rest-options"><label class="rest-option"><input id="srCool" type="checkbox" checked ${coolTotal()===0?'disabled':''}><span><b>Cool Points</b><small>${coolUsed()?`Obnoví ${coolUsed()} spotřebovaných bodů.`:'Momentálně jsou plné.'}</small></span></label><label class="rest-option"><input id="srFeatures" type="checkbox" checked><span><b>Short Rest features</b><small>${res.features.length?esc(res.features.join(' • ')):'Žádné spotřebované Short Rest features.'}</small></span></label><label class="rest-option"><input id="srRelics" type="checkbox" checked><span><b>Relikvie obnovované po Short Rest</b><small>${res.relics.length?esc(res.relics.join(' • ')):'Žádné takové náboje nejsou spotřebované.'}</small></span></label></div></div>${preview!==h.current?`<div class="rest-result">Po zvolených Hit Dice bude HP nejvýše ${preview}/${h.max}; přesné léčení určí hod.</div>`:''}`;$('#finishShortRest').disabled=!can}
  function openShortRest(){shortRestDice=0;renderShortRestBody();$('#shortRestDialog').showModal()}
  function rollDie(sides){return 1+Math.floor(Math.random()*sides)}
  function finishShortRest(){if(state().character.hp.current<=0){toast('Krátký odpočinek vyžaduje alespoň 1 HP.','warn');return}const dice=Math.min(shortRestDice,hitDiceAvailable()),rolls=[];let healing=0;for(let i=0;i<dice;i++){const roll=rollDie(10),gain=Math.max(1,roll+abilityMod('CON'));rolls.push(`${roll}${abilityMod('CON')>=0?'+':''}${abilityMod('CON')}=${gain}`);healing+=gain}const cool=$('#srCool')?.checked,features=$('#srFeatures')?.checked,relics=$('#srRelics')?.checked;S.update(s=>{if(dice){s.character.hitDice.d10.spent=(Number(s.character.hitDice.d10.spent)||0)+dice;s.character.hp.current=Math.min(s.character.hp.max,s.character.hp.current+healing)}if(cool)s.classes.treasureHunter.coolUsed=0;if(features){Object.keys(s.classes.treasureHunter.featureUses||{}).forEach(id=>{const f=featureById(id);if(f?.recovery==='SR')s.classes.treasureHunter.featureUses[id]=0})}if(relics){(s.classes.treasureHunter.relics||[]).forEach(x=>{if(typeof x==='string')return;const r=relicById(x.id);if(r?.recovery==='SR')x.used=0})}});$('#shortRestDialog').close();const rollText=rolls.length?` • ${rolls.join(', ')} • +${healing} HP`:'';toast(`Krátký odpočinek dokončen${rollText}.`);renderAll()}

  function renderLongRestBody(){const h=state().character.hp,can=h.current>0;const spent=hitDiceSpent();$('#longRestBody').innerHTML=`${!can?'<div class="rest-warning">Dlouhý odpočinek můžeš podle D&D 2024 zahájit jen s alespoň 1 HP.</div>':''}${restSummaryHtml()}<div class="rest-card"><h3>Co obnovit</h3><p>Výchozí volby odpovídají D&D 2024 a Treasure Hunter zdrojům. Jednotlivé položky můžeš odškrtnout, pokud řešíš přerušený odpočinek nebo house rule.</p><div class="rest-options"><label class="rest-option"><input id="lrHp" type="checkbox" checked><span><b>Všechny ztracené HP</b><small>${h.max-h.current>0?`Obnoví ${h.max-h.current} HP.`:'HP jsou plné.'}</small></span></label><label class="rest-option"><input id="lrHitDice" type="checkbox" checked><span><b>Všechny Hit Dice</b><small>${spent?`Vrátí ${spent} utracených d10.`:'Všechny d10 jsou dostupné.'}</small></span></label><label class="rest-option"><input id="lrExhaustion" type="checkbox" checked ${exhaustion()===0?'disabled':''}><span><b>Snížit Vyčerpání o 1</b><small>${exhaustion()?`${exhaustion()} → ${Math.max(0,exhaustion()-1)}`:'Žádné Vyčerpání.'}</small></span></label><label class="rest-option"><input id="lrCool" type="checkbox" checked ${coolTotal()===0?'disabled':''}><span><b>Cool Points</b><small>Obnoví všechny Cool Points.</small></span></label><label class="rest-option"><input id="lrFeatures" type="checkbox" checked><span><b>Class features</b><small>Obnoví zdroje s Short Rest i Long Rest obnovou.</small></span></label><label class="rest-option"><input id="lrRelics" type="checkbox" checked><span><b>Náboje relikvií</b><small>Obnoví náboje, které se vrací po Short nebo Long Rest.</small></span></label></div></div>`;$('#finishLongRest').disabled=!can}
  function openLongRest(){renderLongRestBody();$('#longRestDialog').showModal()}
  function finishLongRest(){if(state().character.hp.current<=0){toast('Dlouhý odpočinek vyžaduje alespoň 1 HP.','warn');return}const opts={hp:$('#lrHp')?.checked,hd:$('#lrHitDice')?.checked,ex:$('#lrExhaustion')?.checked,cool:$('#lrCool')?.checked,features:$('#lrFeatures')?.checked,relics:$('#lrRelics')?.checked};S.update(s=>{if(opts.hp)s.character.hp.current=s.character.hp.max;if(opts.hd)s.character.hitDice.d10.spent=0;if(opts.ex)s.character.exhaustion=Math.max(0,(Number(s.character.exhaustion)||0)-1);if(opts.cool)s.classes.treasureHunter.coolUsed=0;if(opts.features)resetFeatures(s,'LR');if(opts.relics)resetRelics(s,'LR')});$('#longRestDialog').close();toast('Dlouhý odpočinek dokončen.');renderAll()}

  function formulaHtml(total,rows,note='',edit=''){return `<div class="breakdown"><div class="breakdown-total"><span>Výsledná hodnota</span><b>${esc(total)}</b></div><div class="formula-list">${rows.map(r=>`<div class="formula-row ${r.cls||''}"><span>${esc(r.label)}</span><span>${esc(r.value)}</span></div>`).join('')}</div>${note?`<div class="detail-note">${esc(note)}</div>`:''}${edit?`<div class="detail-edit">${edit}</div>`:''}</div>`}
  function fillDetail(key){activeDetailKey=key;let title='Detail',body='';const [kind,argRaw]=key.split(':'),arg=argRaw?decodeURIComponent(argRaw):'';
    if(kind==='ac'){title='Obranné číslo';body=formulaHtml(state().character.ac,[{label:'Uložené AC',value:state().character.ac}],'V7s zatím ukládá AC přímo. Až přidáme kompletní armor/equipment builder, rozpad se bude počítat z vybavení.',`<label>Upravit AC<input type="number" min="0" value="${state().character.ac}" data-detail-edit="ac"></label>`)}
    else if(kind==='initiative'){title='Iniciativa';body=formulaHtml(signed(initiative()),[{label:'DEX modifier',value:signed(abilityMod('DEX'))},{label:'Vlastní bonus',value:signed(Number(state().character.initiativeBonus)||0)},{label:`Vyčerpání ${exhaustion()}`,value:signed(d20Penalty()),cls:exhaustion()?'penalty':''}],conditions().includes('Incapacitated')?'Vyřazený stav dává při hodu iniciativy Nevýhodu. Číselný bonus se tím nemění.':'Iniciativa je Dexterity ability check, takže Vyčerpání se na ni vztahuje.',`<label>Vlastní bonus k iniciativě<input type="number" value="${Number(state().character.initiativeBonus)||0}" data-detail-edit="initiativeBonus"></label>`)}
    else if(kind==='speed'){const zero=R.speedIsZero(conditions())||exhaustion()>=6;title='Rychlost';body=formulaHtml(`${derivedSpeed()} ft`,[{label:'Základní Rychlost',value:`${state().character.speed} ft`},{label:'Bonus z připravených relikvií',value:`+${relicSpeedBonus()} ft`,cls:relicSpeedBonus()?'bonus':''},{label:`Vyčerpání ${exhaustion()}`,value:`−${R.exhaustionSpeedPenalty(exhaustion())} ft`,cls:exhaustion()?'penalty':''}],zero?'Aktivní stav nastavuje Rychlost na 0 a tato hodnota nemůže být zvýšena.':'Vyčerpání v D&D 2024 snižuje Rychlost o 5 ft za úroveň.',`<label>Základní Rychlost<input type="number" min="0" step="5" value="${state().character.speed}" data-detail-edit="speed"></label>`)}
    else if(kind==='pb'){title='Bonus zdatnosti';body=formulaHtml(signed(pb()),[{label:'Úroveň postavy',value:level()},{label:'Progression',value:'2 + floor((level − 1) / 4)'}],'Bonus zdatnosti se odvozuje z úrovně a neupravuje se ručně.')}
    else if(kind==='whipDC'||kind==='ropeDC'){title=kind==='whipDC'?'DC biče':'DC lana';body=formulaHtml(whipDC(),[{label:'Základ',value:8},{label:'PB',value:signed(pb())},{label:'DEX modifier',value:signed(abilityMod('DEX'))}],'DC není D20 Test, proto se na něj Vyčerpání nevztahuje.')}
    else if(kind==='relicDC'){title='DC relikvií';body=formulaHtml(relicDC(),[{label:'Základ',value:8},{label:'PB',value:signed(pb())},{label:'INT modifier',value:signed(abilityMod('INT'))}],'DC není D20 Test, proto se na něj Vyčerpání nevztahuje.')}
    else if(kind==='cool'){title='Cool';body=formulaHtml(level()<2?coolDie():`${coolAvailable()}/${coolTotal()} • ${coolDie()}`,[{label:'Úroveň Treasure Huntera',value:level()},{label:'Maximum Cool Points',value:coolTotal()},{label:'Spotřebováno',value:coolUsed()},{label:'Cool Die',value:coolDie()}],'Cool Points se obnovují po krátkém nebo dlouhém odpočinku. Cool Die roste s úrovní.')}
    else if(kind==='hitDice'){title='Hit Dice';body=formulaHtml(`${hitDiceAvailable()}/${level()} d10`,[{label:'Celkem',value:`${level()}d10`},{label:'Utraceno',value:`${hitDiceSpent()}d10`},{label:'Dostupné',value:`${hitDiceAvailable()}d10`},{label:'CON modifier k léčení',value:signed(abilityMod('CON'))}],'Během krátkého odpočinku můžeš utrácet Hit Dice na léčení. Dlouhý odpočinek v pravidlech D&D 2024 obnoví všechny utracené Hit Dice.')}
    else if(kind==='exhaustion'){title='Vyčerpání';body=formulaHtml(exhaustion(),[{label:'Úroveň',value:`${exhaustion()} / 6`},{label:'Postih k D20 Testům',value:signed(d20Penalty()),cls:exhaustion()?'penalty':''},{label:'Postih k Rychlosti',value:`−${R.exhaustionSpeedPenalty(exhaustion())} ft`,cls:exhaustion()?'penalty':''}],exhaustion()>=6?'Úroveň 6 znamená smrt postavy.':'Dlouhý odpočinek sníží Vyčerpání o 1.',`<div class="detail-actions-row"><button type="button" class="small-btn" data-exhaustion="-1">− Vyčerpání</button><button type="button" class="small-btn danger" data-exhaustion="1">+ Vyčerpání</button></div>`)}
    else if(kind==='ability'){const a=arg,sv=saveMod(a);title=`${a} • vlastnost a save`;body=formulaHtml(`${ability(a)} / ${signed(abilityMod(a))}`,[{label:'Hodnota vlastnosti',value:ability(a)},{label:'Modifier',value:`floor((${ability(a)} − 10) / 2) = ${signed(abilityMod(a))}`},{label:'Save proficiency',value:T.saves.includes(a)?`Ano • +${pb()}`:'Ne'},{label:'Vyčerpání k D20 Testu',value:signed(d20Penalty()),cls:exhaustion()?'penalty':''},{label:'Výsledný save',value:saveAutoFails(a)?'AUTO FAIL':signed(sv)}],saveAutoFails(a)?'Aktivní stav způsobuje automatický neúspěch STR/DEX save.':'Modifier vlastnosti samotný Vyčerpání nemění; postih se přičte až k D20 Testu.',`<label>Upravit ${a}<input type="number" min="1" max="30" value="${ability(a)}" data-detail-edit="ability:${a}"></label>`)}
    else if(kind==='skill'){const n=arg,a=ALL_SKILLS[n],st=skillStatus(n),prof=st===2?'Odbornost':st===1?'Zdatnost':'Bez zdatnosti';title=n;body=formulaHtml(signed(skillMod(n)),[{label:`${a} modifier`,value:signed(abilityMod(a))},{label:prof,value:st?signed(pb()*st):'+0'},{label:`Vyčerpání ${exhaustion()}`,value:signed(d20Penalty()),cls:exhaustion()?'penalty':''}],conditions().includes('Poisoned')?'Otrávený stav dává na ability checks Nevýhodu.':conditions().includes('Frightened')?'Vystrašený stav může dát na ability checks Nevýhodu, pokud vidíš zdroj strachu.':'Skill check je ability check a tedy D20 Test.',`<label>Zdatnost<select data-detail-edit="skill:${encodeURIComponent(n)}"><option value="0" ${st===0?'selected':''}>Bez zdatnosti</option><option value="1" ${st===1?'selected':''}>Zdatnost</option><option value="2" ${st===2?'selected':''}>Odbornost</option></select></label>`)}
    else if(kind==='condition'){const info=R.CONDITIONS[arg];title=info?.name||arg;body=`<div class="breakdown"><div class="detail-note">${esc(info?.summary||'Vlastní stav.')}</div><div class="detail-actions-row"><button type="button" class="small-btn danger" data-remove-condition="${esc(arg)}">Odebrat stav</button></div></div>`}
    else{title='Detail';body='<div class="empty">Pro tuto hodnotu zatím není rozpad dostupný.</div>'}
    $('#detailTitle').textContent=title;$('#detailBody').innerHTML=body;
  }
  function openDetail(key){fillDetail(key);if(!$('#detailDialog').open)$('#detailDialog').showModal()}

  function openEdit(){const s=state();$('#editName').value=s.character.name||'';$('#editRace').value=s.character.race||'';$('#editLevel').value=level();$('#editHpMax').value=s.character.hp.max;$('#editHpAuto').checked=s.character.hp.auto!==false;$('#editHpMax').disabled=$('#editHpAuto').checked;$('#editAc').value=s.character.ac;$('#editSpeed').value=s.character.speed;$('#editInitBonus').value=s.character.initiativeBonus||0;$('#abilityEditor').innerHTML=S.A.map(a=>`<label>${a}<input type="number" min="1" max="30" value="${ability(a)}" data-edit-ability="${a}"></label>`).join('');$('#editPortrait').value='';$('#portraitPreview').innerHTML=s.character.portrait?`<img src="${s.character.portrait}" alt="">`:'<span>Bez portrétu</span>';$('#editDialog').showModal()}
  async function saveEdit(ev){ev.preventDefault();const old=state(),oldMax=old.character.hp.max,oldCurrent=old.character.hp.current,damage=Math.max(0,oldMax-oldCurrent),newLevel=Math.max(1,Math.min(20,Number($('#editLevel').value)||1));let portrait=old.character.portrait||'';const file=$('#editPortrait').files[0];if(file){try{portrait=await S.imageToThumb(file)}catch(e){}}const scores={};$$('[data-edit-ability]').forEach(inp=>scores[inp.dataset.editAbility]=Math.max(1,Math.min(30,Number(inp.value)||10)));const conMod=mod(scores.CON),auto=$('#editHpAuto').checked,newMax=auto?T.hpMax(newLevel,conMod):Math.max(1,Number($('#editHpMax').value)||1);S.update(s=>{s.character.name=$('#editName').value.trim();s.character.race=$('#editRace').value.trim();s.character.level=newLevel;s.character.portrait=portrait;s.character.hp.auto=auto;s.character.hp.max=newMax;s.character.hp.current=Math.max(0,Math.min(newMax,newMax-damage));s.character.ac=Math.max(0,Number($('#editAc').value)||0);s.character.speed=Math.max(0,Number($('#editSpeed').value)||0);s.character.initiativeBonus=Number($('#editInitBonus').value)||0;s.character.abilities=scores;s.classes.treasureHunter.coolUsed=Math.min(Number(s.classes.treasureHunter.coolUsed)||0,T.coolTotal(newLevel));s.character.hitDice.d10.spent=Math.min(Number(s.character.hitDice.d10.spent)||0,newLevel)});$('#editDialog').close();toast('Postava uložena.');renderAll()}

  async function saveNpc(ev){ev.preventDefault();const idx=$('#npcId').value===''?null:Number($('#npcId').value),existing=idx==null?{}:(state().campaign.npcs||[])[idx]||{};let image=existing.image||'';const file=$('#npcImage').files[0];if(file){try{image=await S.imageToThumb(file,360,.74)}catch(e){}}const n={...existing,name:$('#npcName').value.trim()||'NPC',tag:$('#npcTag').value.trim(),location:$('#npcLocation').value.trim(),notes:$('#npcNotes').value.trim(),image};S.update(s=>{if(!Array.isArray(s.campaign.npcs))s.campaign.npcs=[];if(idx==null)s.campaign.npcs.push(n);else s.campaign.npcs[idx]=n});$('#npcDialog').close();toast('NPC uloženo.');renderAll()}
  function openNpc(i){const n=i==null?{}:(state().campaign.npcs||[])[i]||{};$('#npcId').value=i==null?'':String(i);$('#npcName').value=n.name||'';$('#npcTag').value=n.tag||'';$('#npcLocation').value=n.location||'';$('#npcNotes').value=n.notes||'';$('#npcImage').value='';$('#npcDialog').showModal()}

  function globalResults(q){q=q.trim().toLowerCase();if(!q)return[];const out=[];T.features.filter(f=>f.level<=level()).forEach(f=>{if(`${f.name} ${f.summary}`.toLowerCase().includes(q))out.push({type:'FEATURE',title:f.name,page:3,id:f.id})});T.relics.filter(r=>r.level<=level()).forEach(r=>{if(`${r.name} ${r.summary}`.toLowerCase().includes(q))out.push({type:'RELIK VIE',title:r.name,page:4,id:r.id})});(state().campaign.npcs||[]).forEach((n,i)=>{if(`${n.name} ${n.tag} ${n.location} ${n.notes}`.toLowerCase().includes(q))out.push({type:'NPC',title:n.name,page:6,id:String(i)})});return out.slice(0,30)}
  function renderGlobalSearch(){const res=globalResults($('#globalSearch').value);$('#globalSearchResults').innerHTML=res.map(r=>`<button type="button" class="search-result" data-search-jump="${r.page}" data-search-id="${esc(r.id)}"><small>${r.type}</small><strong>${esc(r.title)}</strong></button>`).join('')||($('#globalSearch').value?'<div class="empty">Nic nenalezeno.</div>':'')}

  function addCondition(key){if(!key)return;if(conditionImmunities().includes(key)){toast(`Imunita vůči stavu: ${R.conditionName(key)}.`,'warn');return}if(conditions().includes(key))return;S.update(s=>s.character.conditions.push(key));toast(`Přidán stav: ${R.conditionName(key)}.`,'warn');renderAll()}
  function removeCondition(key){S.update(s=>s.character.conditions=(s.character.conditions||[]).filter(x=>x!==key));toast(`Odebrán stav: ${R.conditionName(key)}.`);renderAll();if($('#detailDialog').open)$('#detailDialog').close()}
  function setExhaustion(delta){const before=exhaustion();S.update(s=>s.character.exhaustion=Math.max(0,Math.min(6,(Number(s.character.exhaustion)||0)+Number(delta))));const after=exhaustion();toast(`Vyčerpání ${before} → ${after}.`,after>before?'warn':'success');renderAll();if($('#detailDialog').open&&activeDetailKey==='exhaustion')fillDetail('exhaustion')}
  function updateDefenseValueSelect(){const type=$('#defenseType')?.value||'resistance',el=$('#defenseValue');if(el)el.innerHTML=defenseValueOptions(type)}
  function addDefense(){const type=$('#defenseType')?.value,value=$('#defenseValue')?.value,key=DEFENSE_ARRAY[type];if(!key||!value)return;S.update(s=>{const arr=s.character.damageDefenses[key]||(s.character.damageDefenses[key]=[]);if(!arr.includes(value))arr.push(value)});toast(`${R.DEFENSE_TYPES[type]} přidána.`);renderAll()}
  function removeDefense(spec){const [type,iRaw]=spec.split(':'),key=DEFENSE_ARRAY[type],i=Number(iRaw);if(!key)return;S.update(s=>s.character.damageDefenses[key].splice(i,1));toast(`${R.DEFENSE_TYPES[type]} odebrána.`);renderAll()}

  function handleDetailEdit(el){const key=el.dataset.detailEdit,val=el.value;if(key==='ac')S.update(s=>s.character.ac=Math.max(0,Number(val)||0));else if(key==='speed')S.update(s=>s.character.speed=Math.max(0,Number(val)||0));else if(key==='initiativeBonus')S.update(s=>s.character.initiativeBonus=Number(val)||0);else if(key?.startsWith('ability:')){const a=key.split(':')[1];S.update(s=>s.character.abilities[a]=Math.max(1,Math.min(30,Number(val)||10)))}else if(key?.startsWith('skill:')){const n=decodeURIComponent(key.slice(6));S.update(s=>{s.character.skills||(s.character.skills={});s.character.skills[n]=Math.max(0,Math.min(2,Number(val)||0))})}renderAll();fillDetail(activeDetailKey);toast('Hodnota upravena.')}

  function bind(){
    initDots();$('#pager').addEventListener('scroll',onPagerScroll,{passive:true});$('#prevPage').onclick=()=>setPage(currentPageIndex()-1);$('#nextPage').onclick=()=>setPage(currentPageIndex()+1);$('#pageDots').onclick=e=>{const b=e.target.closest('[data-page-dot]');if(b)setPage(Number(b.dataset.pageDot))};
    $('#editBtn').onclick=openEdit;$('#saveEdit').onclick=saveEdit;$('#searchBtn').onclick=()=>{$('#globalSearch').value='';$('#globalSearchResults').innerHTML='';$('#searchDialog').showModal();setTimeout(()=>$('#globalSearch').focus(),30)};$('#globalSearch').oninput=renderGlobalSearch;$('#saveNpc').onclick=saveNpc;
    $('#hpMinus').onclick=()=>updateHpAmount(-1);$('#hpPlus').onclick=()=>updateHpAmount(1);$('#hpDamage').onclick=()=>applyHp('damage');$('#hpHeal').onclick=()=>applyHp('heal');$('#hpDamageType').onchange=updateHpDamageNote;$('#hpTemp').oninput=()=>{$('#hpTempRead').textContent=Math.max(0,Number($('#hpTemp').value)||0)};
    $('#finishShortRest').onclick=finishShortRest;$('#finishLongRest').onclick=finishLongRest;
    document.addEventListener('pointerdown',e=>{const b=e.target.closest('button');if(b&&!b.disabled)b.classList.add('pressed')},{passive:true});['pointerup','pointercancel'].forEach(ev=>document.addEventListener(ev,e=>{const b=e.target.closest?.('button');if(b)b.classList.remove('pressed')},{passive:true}));
    document.addEventListener('click',e=>{
      const button=e.target.closest('button');
      if(button?.dataset.removeCondition){e.stopPropagation();removeCondition(button.dataset.removeCondition);return}
      if(button?.dataset.removeDefense){removeDefense(button.dataset.removeDefense);return}
      if(button?.dataset.skillCycle){e.stopPropagation();S.update(s=>{s.character.skills||(s.character.skills={});s.character.skills[button.dataset.skillCycle]=((Number(s.character.skills[button.dataset.skillCycle])||0)+1)%3});toast('Zdatnost skillu změněna.');renderSkills();return}
      const detail=e.target.closest('[data-detail]');if(detail){openDetail(detail.dataset.detail);return}
      const t=e.target.closest('button,[data-edit-npc]');if(!t)return;
      if(t.hasAttribute('data-open-hp')){openHp();return}if(t.hasAttribute('data-open-edit')){openEdit();return}
      if(t.hasAttribute('data-short-rest')){openShortRest();return}if(t.hasAttribute('data-long-rest')){openLongRest();return}
      if(t.dataset.shortDice){shortRestDice=Math.max(0,Math.min(hitDiceAvailable(),shortRestDice+Number(t.dataset.shortDice)));renderShortRestBody();return}
      if(t.dataset.exhaustion){setExhaustion(Number(t.dataset.exhaustion));return}
      if(t.hasAttribute('data-add-condition')){addCondition($('#conditionSelect')?.value);return}
      if(t.hasAttribute('data-add-defense')){addDefense();return}
      if(t.dataset.toggleRow){document.querySelector(`[data-row="${CSS.escape(t.dataset.toggleRow)}"]`)?.classList.toggle('open');return}
      if(t.hasAttribute('data-inspiration')){S.update(s=>s.character.inspiration=!s.character.inspiration);toast(state().character.inspiration?'Inspirace zapnuta.':'Inspirace vypnuta.');renderAll();return}
      if(t.dataset.cool){S.update(s=>s.classes.treasureHunter.coolUsed=Math.max(0,Math.min(coolTotal(),(Number(s.classes.treasureHunter.coolUsed)||0)+Number(t.dataset.cool))));toast('Cool Points upraveny.');renderAll();return}
      if(t.dataset.coolSet){const a=Number(t.dataset.coolSet);S.update(s=>s.classes.treasureHunter.coolUsed=Math.max(0,coolTotal()-a));toast(`Cool dostupné: ${a}.`);renderAll();return}
      if(t.dataset.useAction){const a=allActions().find(x=>x.id===t.dataset.useAction)||featureById(t.dataset.useAction);if(a&&spendCool(a.cost||0)){const f=actionSourceFeature(a);if(f?.uses)useFeature(f.id);else renderAll()}return}
      if(t.dataset.useFeature){useFeature(t.dataset.useFeature);return}
      if(t.dataset.actionFilter){actionFilter=t.dataset.actionFilter;renderActions();return}if(t.dataset.featureFilter){featureFilter=t.dataset.featureFilter;renderFeatures();return}
      if(t.dataset.favorite){S.update(s=>{const a=s.ui.favoriteFeatures||(s.ui.favoriteFeatures=[]),i=a.indexOf(t.dataset.favorite);i>=0?a.splice(i,1):a.push(t.dataset.favorite)});toast('Oblíbené upraveno.');renderFeatures();return}
      if(t.hasAttribute('data-add-relic')){const id=$('#relicSelect')?.value,lim=relicLimit();if(!id)return;if(selectedRelics().length>=lim[2]){toast('Sbírka je plná.','warn');return}S.update(s=>s.classes.treasureHunter.relics.push({id,prepared:false,used:0}));toast('Relikvie přidána.');renderRelics();return}
      if(t.dataset.relicRemove!=null){S.update(s=>s.classes.treasureHunter.relics.splice(Number(t.dataset.relicRemove),1));toast('Relikvie odebrána.');renderAll();return}
      if(t.dataset.relicPrepared!=null){const i=Number(t.dataset.relicPrepared),sel=selectedRelics(),next=!sel[i].prepared;if(next&&sel.filter(r=>r.prepared).length>=relicLimit()[0]){toast('Limit připravených relikvií je plný.','warn');return}S.update(s=>{let r=s.classes.treasureHunter.relics[i];if(typeof r==='string')s.classes.treasureHunter.relics[i]={id:r,prepared:next,used:0};else r.prepared=next});toast(next?'Relikvie připravena.':'Relikvie přesunuta do zálohy.');renderAll();return}
      if(t.dataset.relicUse!=null){const i=Number(t.dataset.relicUse);S.update(s=>{let r=s.classes.treasureHunter.relics[i];if(typeof r==='string'){r={id:r,prepared:false,used:0};s.classes.treasureHunter.relics[i]=r}const def=relicById(r.id),max=def?.charges||0;r.used=Math.min(max,(Number(r.used)||0)+1)});toast('Náboj relikvie spotřebován.');renderAll();return}
      if(t.dataset.relicRefill!=null){S.update(s=>{const r=s.classes.treasureHunter.relics[Number(t.dataset.relicRefill)];if(r&&typeof r==='object')r.used=0});toast('Náboje obnoveny.');renderAll();return}
      if(t.hasAttribute('data-add-item')){const v=$('#newItemName')?.value.trim();if(v)S.update(s=>s.character.gear.inventory.push({name:v,notes:''}));toast('Předmět přidán.');renderGear();return}if(t.dataset.itemRemove!=null){S.update(s=>s.character.gear.inventory.splice(Number(t.dataset.itemRemove),1));toast('Předmět odebrán.');renderGear();return}if(t.dataset.weaponRemove!=null){S.update(s=>s.character.gear.weapons.splice(Number(t.dataset.weaponRemove),1));toast('Zbraň odebrána.');renderAll();return}
      if(t.hasAttribute('data-new-npc')){openNpc(null);return}if(t.dataset.npcFavorite!=null){const i=Number(t.dataset.npcFavorite);S.update(s=>s.campaign.npcs[i].favorite=!s.campaign.npcs[i].favorite);toast('NPC oblíbené upraveno.');renderNpcs();return}if(t.dataset.editNpc!=null&&!t.closest('button')){openNpc(Number(t.dataset.editNpc));return}
      if(t.dataset.searchJump!=null){$('#searchDialog').close();setPage(Number(t.dataset.searchJump));return}
    });
    document.addEventListener('input',e=>{if(e.target.id==='featureSearch'){featureSearch=e.target.value;const pos=e.target.selectionStart;renderFeatures();const n=$('#featureSearch');n?.focus();if(n&&pos!=null)n.setSelectionRange(pos,pos)}if(e.target.dataset.money){const k=e.target.dataset.money,v=Math.max(0,Number(e.target.value)||0);S.update(s=>s.character.gear.money[k]=v)}if(e.target.id==='editHpAuto')$('#editHpMax').disabled=e.target.checked});
    document.addEventListener('change',e=>{if(e.target.id==='defenseType'){updateDefenseValueSelect();return}if(e.target.dataset.detailEdit){handleDetailEdit(e.target);return}});
  }

  document.addEventListener('DOMContentLoaded',()=>{bind();renderAll();requestAnimationFrame(()=>setPage(Number(state().ui.page)||0,false))});
})();