(function(){
  const S=window.V7SStateV7s,T=window.TreasureHunterDataV7s,R=window.DND2024Rules;
  const Roster=window.V7SRoster,Catalog=window.V7SItemCatalog,Cropper=window.V7SPortraitCropper;
  T.relics=window.TreasureHunterRelicsV7s||[];
  const PAGES=['character','actions','skills','features','relics','gear','npcs'];
  const TITLES=['CHARACTER','ACTIONS','SKILLS','FEATURES','RELICS','GEAR','NPCs'];
  const ALL_SKILLS={Acrobatics:'DEX','Animal Handling':'WIS',Arcana:'INT',Athletics:'STR',Deception:'CHA',History:'INT',Insight:'WIS',Intimidation:'CHA',Investigation:'INT',Medicine:'WIS',Nature:'INT',Perception:'WIS',Performance:'CHA',Persuasion:'CHA',Religion:'INT','Sleight of Hand':'DEX',Stealth:'DEX',Survival:'WIS'};
  const CORE_OTHER_ACTIONS=[
    {id:'unarmed-damage',name:'Unarmed Strike — Damage',action:'Action',group:'other',summary:'Make a melee attack using Strength and Proficiency Bonus. On a hit, deal 1 + STR modifier Bludgeoning damage.'},
    {id:'unarmed-grapple',name:'Unarmed Strike — Grapple',action:'Action',group:'other',summary:'Instead of damage, attempt to Grapple a creature no more than one size larger. The target makes a Strength or Dexterity saving throw against 8 + PB + STR modifier.'},
    {id:'unarmed-shove',name:'Unarmed Strike — Shove / Push',action:'Action',group:'other',summary:'Instead of damage, attempt to push the target 5 ft. away or knock it Prone. The target makes a Strength or Dexterity saving throw against 8 + PB + STR modifier.'},
    {id:'dash',name:'Dash',action:'Action',group:'other',summary:'Gain extra movement for the current turn equal to your Speed after modifiers.'},
    {id:'disengage',name:'Disengage',action:'Action',group:'other',summary:'Your movement does not provoke Opportunity Attacks for the rest of the turn.'},
    {id:'dodge',name:'Dodge',action:'Action',group:'other',summary:'Until the start of your next turn, attacks against you have Disadvantage if you can see the attacker, and you make Dexterity saving throws with Advantage.'},
    {id:'help',name:'Help',action:'Action',group:'other',summary:'Assist another creature with a check or attack when the Help action requirements are met.'},
    {id:'hide',name:'Hide',action:'Action',group:'other',summary:'Attempt to become hidden when the environment and line of sight allow it.'},
    {id:'ready',name:'Ready',action:'Action',group:'other',summary:'Choose a trigger and prepare an action to take as a Reaction when that trigger occurs.'},
    {id:'search',name:'Search',action:'Action',group:'other',summary:'Use an appropriate ability or skill to find something that is concealed or not obvious.'},
    {id:'study',name:'Study',action:'Action',group:'other',summary:'Use an appropriate Intelligence-based check to recall or discover useful information.'},
    {id:'utilize',name:'Utilize',action:'Action',group:'other',summary:'Use a nonmagical object whose use requires an action.'},
    {id:'object-interaction',name:'Simple Object Interaction',action:'Free',group:'free',summary:'A simple interaction such as drawing, stowing, opening, or handling an object can often be done without spending an Action, subject to the rules and GM.'}
  ];
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const importedText=v=>String(v??'').replace(/hromov(?:é|ého) (?:zranění|poškození)/gi,'Thunder damage').replace(/Hromov(?:é|ého) (?:zranění|poškození)/g,'Thunder damage');
  const signed=S.signed,mod=S.modifier;
  let actionFilter='all',featureFilter='all',featureSearch='',hpAmount=1,raf=0,savePageTimer=0,pendingPortrait='',catalogQuery='',catalogRarity='all',catalogKind='all';

  const state=()=>S.get();
  const level=()=>Math.max(1,Math.min(20,Number(state().character.level)||1));
  const pb=()=>T.pb(level());
  const coolTotal=()=>T.coolTotal(level());
  const coolUsed=()=>Math.max(0,Math.min(coolTotal(),Number(state().classes.treasureHunter.coolUsed)||0));
  const coolAvailable=()=>Math.max(0,coolTotal()-coolUsed());
  const coolDie=()=>T.coolDie(level());
  const ability=a=>Number(state().character.abilities[a])||10;
  const abilityMod=a=>mod(ability(a));
  const conditions=()=>Array.isArray(state().character.conditions)?state().character.conditions:[];
  const exhaustion=()=>Math.max(0,Math.min(6,Number(state().character.exhaustion)||0));
  const d20Penalty=()=>R.exhaustionPenalty(exhaustion());
  const saveAutoFails=a=>R.saveAutoFails(conditions(),a)||exhaustion()>=6;
  const saveMod=a=>saveAutoFails(a)?null:abilityMod(a)+(T.saves.includes(a)?pb():0)+d20Penalty();
  const initiative=()=>abilityMod('DEX')+(Number(state().character.initiativeBonus)||0)+d20Penalty();
  const relicDC=()=>8+pb()+abilityMod('INT');
  const whipRopeDC=()=>8+pb()+abilityMod('DEX');
  const relicLimit=()=>T.relicLimit(level());
  const skillStatus=n=>Math.max(0,Math.min(2,Number(state().character.skills?.[n])||0));
  const skillMod=n=>abilityMod(ALL_SKILLS[n])+(skillStatus(n)?pb()*skillStatus(n):0)+d20Penalty();

  function selectedRelics(){return (state().classes.treasureHunter.relics||[]).map((r,i)=>typeof r==='string'?{id:r,prepared:false,used:0,stateIndex:i}:{prepared:false,used:0,...r,stateIndex:i})}
  function relicById(id){return T.relics.find(r=>r.id===id)}
  function activeRelics(){return selectedRelics().filter(r=>r.prepared).map(r=>({...relicById(r.id),...r})).filter(Boolean)}
  function relicMax(r){return r.uses==='PB'?pb():Math.max(0,Number(r.charges)||0)}
  function derivedSpeed(){if(exhaustion()>=6||R.speedIsZero(conditions()))return 0;return Math.max(0,(Number(state().character.speed)||0)+activeRelics().reduce((n,r)=>n+(Number(r.bonusSpeed)||0),0)-R.exhaustionSpeedPenalty(exhaustion()))}
  function derivedSenses(){const out=[...(state().character.proficiencies.senses||[])];activeRelics().forEach(r=>{if(r.truesight)out.push(`Truesight ${r.truesight} ft.`);if(r.darkvision)out.push(`Darkvision +${r.darkvision} ft.`)});return [...new Set(out)]}
  function conditionImmunities(){const out=[...(state().character.damageDefenses?.conditionImmunities||[])];if(activeRelics().some(r=>r.id==='last-exorcists-testament'))out.push('Charmed','Frightened');if(conditions().includes('Petrified'))out.push('Poisoned');return [...new Set(out)]}
  function derivedDefenses(){const out=[],d=state().character.damageDefenses||{};(d.resistances||[]).forEach(x=>out.push(`Resistances: ${R.damageTypeName(x)}`));(d.immunities||[]).forEach(x=>out.push(`Immunities: ${R.damageTypeName(x)}`));(d.vulnerabilities||[]).forEach(x=>out.push(`Vulnerabilities: ${R.damageTypeName(x)}`));conditionImmunities().forEach(x=>out.push(`Condition Immunities: ${R.conditionName(x)}`));if(activeRelics().some(r=>r.id==='cloak-pilgrim-worlds'))out.push('Resistances: selected Cloak damage type');if(conditions().includes('Petrified'))out.push('Resistances: all damage while Petrified');return [...new Set(out)]}
  function combineMode(a,b){if(a==='normal')return b;if(b==='normal')return a;if(a!==b)return'normal';return a}
  function initiativeMode(){let m=state().character.rollModes?.initiative||'normal';if(activeRelics().some(r=>r.id==='silent-pocket-watch'))m=combineMode(m,'advantage');if(R.isIncapacitated(conditions()))m=combineMode(m,'disadvantage');return m}
  function skillMode(name){let m=state().character.rollModes?.skills?.[name]||'normal';if(R.abilityCheckDisadvantage(conditions()).length)m=combineMode(m,'disadvantage');return m}
  function rollFlag(mode,key){const cls=mode==='advantage'?'advantage':mode==='disadvantage'?'disadvantage':'normal',label=mode==='advantage'?'A':mode==='disadvantage'?'D':'±';return `<button class="roll-flag ${cls}" data-roll-cycle="${esc(key)}" aria-label="${esc(mode)}">${label}</button>`}
  function cycleMode(current){return current==='normal'?'advantage':current==='advantage'?'disadvantage':'normal'}
  function pageIntro(title,subtitle){return `<div class="page-intro"><span>${esc(title)}</span><small>${esc(subtitle)}</small></div>`}
  function section(title,body,right=''){return `<section class="section"><div class="section-head"><h2>${title}</h2>${right}</div>${body}</section>`}
  function stat(label,value,cls='',attrs='',flag=''){return `<button class="stat ${cls}" ${attrs}><span>${esc(label)}</span><b>${esc(value)}</b>${flag}</button>`}
  function actionCode(a){if(a==='Action')return'A';if(a==='Bonus Action')return'BA';if(a==='Reaction')return'R';if(a==='Free')return'FREE';if(a==='Other')return'OTHER';if(a==='Special')return'SA';return a==='Resource'?'RES':'PASS'}
  function badgeClass(a){const c=actionCode(a);return c==='A'?'a':c==='BA'?'ba':c==='R'?'r':c==='FREE'?'free':c==='OTHER'?'other':'pass'}
  function rowCard(id,title,meta,detail,action='Passive',extra=''){return `<article class="row-card" data-row="${esc(id)}"><button class="row-main" data-toggle-row="${esc(id)}"><span><strong>${esc(title)}</strong><span class="row-meta">${meta}</span></span><span class="badge ${badgeClass(action)}">${esc(actionCode(action))}</span></button><div class="row-detail">${detail}${extra}</div></article>`}
  function toast(message,type='success'){const host=$('#toastHost');if(!host)return;const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;host.appendChild(el);setTimeout(()=>{el.style.opacity='0';setTimeout(()=>el.remove(),180)},1800)}

  function renderTop(){const s=state();$('#topName').textContent=s.character.name||'Unnamed Character';$('#topClass').textContent=`Treasure Hunter ${level()} • PB ${signed(pb())}`;$('#hudHp').textContent=`${s.character.hp.current}/${s.character.hp.max}`;$('#hudAc').textContent=s.character.ac;$('#hudCool').textContent=level()>=2?`${coolAvailable()}/${coolTotal()} ${coolDie()}`:`— ${coolDie()}`}
  function statusBanner(){const tags=[];if(exhaustion())tags.push(`Exhaustion ${exhaustion()}: D20 ${d20Penalty()}, Speed −${R.exhaustionSpeedPenalty(exhaustion())} ft.`);if(R.isIncapacitated(conditions()))tags.push('Incapacitated');if(R.speedIsZero(conditions()))tags.push('Speed 0');return tags.length?`<div class="status-banner">${tags.map(t=>`<span class="status-tag">${esc(t)}</span>`).join('')}</div>`:''}
  function conditionOptions(){const active=new Set(conditions()),immune=new Set(conditionImmunities());let out=exhaustion()?'':'<option value="Exhaustion">Exhaustion</option>';out+=Object.entries(R.CONDITIONS).filter(([k])=>!active.has(k)&&!immune.has(k)).map(([k,v])=>`<option value="${k}">${esc(v.name)}</option>`).join('');return out}
  function conditionChips(){let out=conditions().map(k=>`<span class="condition-detail-btn" data-detail-condition="${esc(k)}">${esc(R.conditionName(k))}<button data-remove-condition="${esc(k)}">×</button></span>`).join('');if(exhaustion())out+=`<span class="condition-detail-btn exhaustion"><span>Exhaustion</span><button data-exhaustion="-1">−</button><b>${exhaustion()}</b><button data-exhaustion="1">+</button><button data-exhaustion-clear>×</button></span>`;return out||'<span class="muted">No active conditions</span>'}
  function defenseChips(){const d=state().character.damageDefenses||{},map=[['resistance','resistances'],['immunity','immunities'],['vulnerability','vulnerabilities'],['conditionImmunity','conditionImmunities']];let out='';map.forEach(([type,key])=>(d[key]||[]).forEach((v,i)=>out+=`<span class="defense-chip ${type}">${esc(R.DEFENSE_TYPES[type])}: ${esc(type==='conditionImmunity'?R.conditionName(v):R.damageTypeName(v))}<button data-remove-defense="${type}:${i}">×</button></span>`));if(activeRelics().some(r=>r.id==='last-exorcists-testament'))out+=`<span class="defense-chip conditionImmunity">Condition Immunities: Charmed, Frightened</span>`;return out||'<span class="muted">No resistances, immunities, or vulnerabilities</span>'}
  function defenseValueOptions(type){if(type==='conditionImmunity')return Object.keys(R.CONDITIONS).map(k=>`<option value="${k}">${k}</option>`).join('');return R.DAMAGE_TYPES.map(([k,n])=>`<option value="${k}">${n}</option>`).join('')}

  function renderCharacter(){
    const s=state(),hp=s.character.hp,portrait=s.character.portrait?`<img class="hero-portrait" src="${s.character.portrait}" alt="Character portrait">`:`<button class="hero-portrait placeholder" data-open-edit>＋</button>`;
    const abilities=S.A.map(a=>{const sm=saveMod(a);return `<button class="ability"><div class="abbr">${a}</div><div class="mod">${signed(abilityMod(a))}</div><div class="score">${ability(a)}</div><div class="save ${T.saves.includes(a)?'prof':''}">${sm==null?'AUTO FAIL':`${T.saves.includes(a)?'●':'○'} ${signed(sm)}`}</div></button>`}).join('');
    let dots='';for(let i=0;i<coolTotal();i++){const filled=i<coolAvailable();dots+=`<button class="cool-dot ${filled?'filled':''}" data-cool-toggle="${filled?'spend':'restore'}" aria-label="${filled?'Spend':'Restore'} Cool Point"></button>`}
    const senses=[...derivedSenses(),...derivedDefenses()];
    const cond=`<div class="condition-strip">${conditionChips()}</div><div class="manager-row top-gap"><select id="conditionSelect"><option value="">Add condition…</option>${conditionOptions()}</select><button data-add-condition>+</button></div>`;
    const defs=`<div class="condition-strip">${defenseChips()}</div><div class="manager-row two-select top-gap"><select id="defenseType"><option value="resistance">Resistances</option><option value="immunity">Immunities</option><option value="vulnerability">Vulnerabilities</option><option value="conditionImmunity">Condition Immunities</option></select><select id="defenseValue">${defenseValueOptions('resistance')}</select><button data-add-defense>+</button></div>`;
    $('#characterPage').innerHTML=`${pageIntro('CHARACTER','Character overview')}${statusBanner()}${section('',`<div class="character-hero">${portrait}<div class="hero-copy"><span class="eyebrow">TREASURE HUNTER ${level()}</span><h1>${esc(s.character.name||'Unnamed Character')}</h1><p>${esc(s.character.race||'')}</p></div></div><div class="stat-grid hero-stats">${stat('HP',`${hp.current}/${hp.max}`,'hp-stat','data-open-hp')}${stat('AC',s.character.ac)}${stat('INIT',signed(initiative()),'','',''+rollFlag(initiativeMode(),'initiative'))}${stat('SPEED',`${derivedSpeed()} ft.`)}</div><div class="hero-actions"><button class="small-btn ${s.character.inspiration?'primary':''}" data-inspiration>✦ Inspiration</button><button class="small-btn" data-short-rest>Short Rest</button><button class="small-btn" data-long-rest>Long Rest</button></div>`)}${section('Cool Points',level()<2?`<span class="muted">Cool Points unlock at level 2. Cool Die: ${coolDie()}.</span>`:`<div class="resource-row"><div><div class="eyebrow">${coolAvailable()} / ${coolTotal()} • ${coolDie()}</div><div class="cool-dots">${dots}</div></div></div>`)}${section('Abilities & Saving Throws',`<div class="ability-grid">${abilities}</div>`)}${section('Class DC',`<div class="stat-grid dc-grid">${stat('WHIP / ROPE DC',whipRopeDC(),'compact')}${stat('RELIC DC',relicDC(),'compact')}${stat('PB',signed(pb()),'compact')}</div>`)}${senses.length?section('Senses & Defenses',`<div class="condition-strip">${senses.map(x=>`<span class="chip brass">${esc(x)}</span>`).join('')}</div>`):''}${section('Conditions',cond)}${section('Defenses',defs)}`;
  }

  function allClassActions(){const out=[];T.features.filter(f=>f.level<=level()).forEach(f=>{if(f.action&&!['Passive','Resource'].includes(f.action))out.push({id:f.id,name:f.name,action:f.action,summary:f.fullText||f.summary,cost:f.cost||0,source:f.name});(f.actions||[]).forEach(a=>out.push({...a,source:f.name,level:f.level}))});return out}
  function weaponActions(){return (state().character.gear.weapons||[]).map(w=>({id:`weapon-${w.id||w.name}`,name:w.name,action:'Action',group:'attack',source:'Weapon',summary:`Attack ${signed(abilityMod(w.attackAbility||'DEX')+pb())} • ${w.damage||''} ${w.damageType||''} + ${signed(abilityMod(w.attackAbility||'DEX'))}${w.mastery?` • Mastery: ${w.mastery}`:''}`}))}
  function allActions(){return [...weaponActions(),...allClassActions(),...activeRelics().filter(r=>r.action!=='Passive').map(r=>({id:`relic-${r.id}`,name:r.name,action:r.action,summary:r.fullText||r.summary,source:'Relic',group:'relic'})),...CORE_OTHER_ACTIONS,...(state().character.customActions||[])]}
  function matchesAction(a){if(actionFilter==='all')return true;if(actionFilter==='other')return a.group==='other'||a.action==='Other';if(actionFilter==='free')return a.action==='Free'||a.group==='free';if(a.group==='other')return false;const c=actionCode(a.action).toLowerCase();return c===actionFilter}
  function renderActions(){const filters=[['all','ALL'],['a','A'],['ba','BA'],['r','R'],['free','FREE'],['other','OTHER']].map(([k,l])=>`<button class="filter-btn ${actionFilter===k?'active':''}" data-action-filter="${k}">${l}</button>`).join('');const rows=allActions().filter(matchesAction).map(a=>rowCard(a.id,a.name,`<span>${esc(a.source||'Custom')}</span>${a.cost?`<span>${a.cost} Cool</span>`:''}`,esc(importedText(a.fullText||a.summary||'')),a.action,`<div class="detail-actions">${a.cost?`<button class="small-btn primary" data-use-action="${esc(a.id)}">Use • −${a.cost} Cool</button>`:''}${a.custom?`<button class="small-btn danger" data-delete-custom-action="${esc(a.id)}">Delete</button>`:''}</div>`)).join('')||'<div class="empty">No actions in this group.</div>';$('#actionsPage').innerHTML=`${pageIntro('ACTIONS','Combat, class, free and other actions')}${section('Actions',`<div class="filters">${filters}</div><button class="small-btn primary top-gap" data-new-action>+ Custom Action</button><div class="list top-gap">${rows}</div>`)}`}

  function renderSkills(){const rows=Object.keys(ALL_SKILLS).map(n=>{const st=skillStatus(n),cls=st===2?'expert':st===1?'prof':'',mode=skillMode(n);return `<div class="skill-row"><button class="prof-dot ${cls}" data-skill-cycle="${esc(n)}">${st===2?'◆':st===1?'●':'○'}</button><span class="skill-name">${esc(n)}</span><span class="skill-ability">${ALL_SKILLS[n]}</span><span class="skill-mod">${signed(skillMod(n))}</span>${rollFlag(mode,`skill:${n}`)}</div>`}).join('');const p=state().character.proficiencies,th=state().classes.treasureHunter;const details=(t,b)=>`<details class="proficiency"><summary>${t}</summary><div class="prof-body">${esc(b||'—')}</div></details>`;const langs=[...(p.languages||[]),...(th.ancientLanguages||[]).filter(Boolean)],veh=[...(p.vehicles||[]),...(th.vehicles||[]).filter(Boolean)];$('#skillsPage').innerHTML=`${pageIntro('SKILLS','Skills & Proficiencies')}${section('Skills',rows)}${section('Proficiencies',`${details('Armor',[...new Set([...T.armor,...(p.armor||[])])].join(' • '))}${details('Weapons',[...new Set([...T.weapons,...(p.weapons||[])])].join(' • '))}${details('Tools',[...new Set(p.tools||[])].join(' • '))}${details('Vehicles',[...new Set(veh)].join(' • '))}${details('Languages',[...new Set(langs)].join(' • '))}`)}`}

  function featureChoiceHtml(f){const defs=T.choiceDefinitions?.[f.id]||[],th=state().classes.treasureHunter;if(!defs.length)return'';return `<div class="feature-choices"><div class="eyebrow">FEATURE CHOICES</div>${defs.map(d=>{let vals=d.key==='expertise'?[th.expertise||'']:(Array.isArray(th[d.key])?th[d.key]:Array(d.count).fill(''));return `<label>${esc(d.label)}${Array.from({length:d.count},(_,i)=>{const val=vals[i]||'';if(d.type==='select'){return `<select data-feature-choice="${d.key}" data-choice-index="${i}"><option value="">Choose…</option>${(T[d.source]||[]).map(x=>`<option value="${esc(x)}" ${x===val?'selected':''}>${esc(x)}</option>`).join('')}</select>`}if(d.type==='skill'){const opts=Object.keys(ALL_SKILLS).filter(x=>skillStatus(x)>0);return `<select data-feature-choice="${d.key}" data-choice-index="0"><option value="">Choose proficient skill…</option>${opts.map(x=>`<option ${x===val?'selected':''}>${esc(x)}</option>`).join('')}</select>`}if(d.type==='weapon'){const opts=(state().character.gear.weapons||[]).map(x=>x.name);return `<select data-feature-choice="${d.key}" data-choice-index="${i}"><option value="">Choose weapon…</option>${opts.map(x=>`<option ${x===val?'selected':''}>${esc(x)}</option>`).join('')}</select>`}return `<input data-feature-choice="${d.key}" data-choice-index="${i}" value="${esc(val)}" placeholder="${esc(d.placeholder||'')}">`}).join('')}</label>`}).join('')}</div>`}
  function featureMatches(f){const q=featureSearch.toLowerCase().trim();if(q&&!`${f.name} ${f.summary} ${f.fullText||''}`.toLowerCase().includes(q))return false;if(featureFilter==='all')return true;if(featureFilter==='active')return f.action!=='Passive'||(f.actions||[]).length;if(featureFilter==='passive')return f.action==='Passive'&&!(f.actions||[]).length;if(featureFilter==='subclass')return f.kind==='subclass';return true}
  function renderFeatures(){const fav=state().ui.favoriteFeatures||[],filters=[['all','ALL'],['active','ACTIVE'],['passive','PASSIVE'],['subclass','SUBCLASS']].map(([k,l])=>`<button class="filter-btn ${featureFilter===k?'active':''}" data-feature-filter="${k}">${l}</button>`).join('');const rows=T.features.filter(f=>f.level<=level()).filter(featureMatches).sort((a,b)=>(fav.includes(a.id)?0:1)-(fav.includes(b.id)?0:1)||a.level-b.level||a.name.localeCompare(b.name)).map(f=>{const sub=(f.actions||[]).map(a=>`<div class="subaction"><b>${esc(a.name)}</b><span>${esc(actionCode(a.action))}</span><p>${esc(importedText(a.fullText||a.summary))}</p></div>`).join('');return rowCard(f.id,f.name,`<span>Level ${f.level}</span>${f.kind==='subclass'?'<span>Occult Collector</span>':''}`,`${esc(importedText(f.fullText||f.summary))}${sub?`<div class="subactions">${sub}</div>`:''}${featureChoiceHtml(f)}`,f.action,`<div class="detail-actions"><button class="favorite ${fav.includes(f.id)?'on':''}" data-favorite="${f.id}">★</button></div>`)}).join('')||'<div class="empty">Nothing found.</div>';$('#featuresPage').innerHTML=`${pageIntro('FEATURES','Treasure Hunter feature library')}${section('Find Feature',`<input id="featureSearch" class="search-inline" value="${esc(featureSearch)}" placeholder="Search features…"><div class="filters top-gap">${filters}</div>`)}${section('Features',`<div class="list">${rows}</div>`,`<span class="eyebrow">LEVEL ${level()}</span>`)}`}

  function renderRelics(){const lim=relicLimit(),sel=selectedRelics().map(x=>({...relicById(x.id),...x})).filter(Boolean).sort((a,b)=>(b.prepared?1:0)-(a.prepared?1:0)||a.level-b.level||a.name.localeCompare(b.name)),prep=sel.filter(r=>r.prepared).length,reserve=sel.length-prep,available=T.relics.filter(r=>r.level<=level()&&!sel.some(x=>x.id===r.id));const cards=sel.map(r=>{const max=relicMax(r),left=Math.max(0,max-(Number(r.used)||0)),dots=max?Array.from({length:max},(_,n)=>`<button class="charge-dot ${n<left?'filled':''}" data-relic-charge="${r.stateIndex}" data-charge-state="${n<left?'full':'empty'}"></button>`).join(''):'';return `<article class="relic-card ${r.prepared?'prepared':''}"><div class="relic-top"><div><div class="eyebrow">${r.prepared?'PREPARED':'RESERVE'} • LVL ${r.level}</div><h3>${esc(r.name)}</h3></div><button class="small-btn" data-relic-remove="${r.stateIndex}">×</button></div><p>${esc(importedText(r.fullText||r.summary||''))}</p>${max?`<div class="charge-row"><span>${left}/${max}</span><div class="charge-dots">${dots}</div></div>`:''}<div class="detail-actions"><button class="small-btn ${r.prepared?'primary':''}" data-relic-prepared="${r.stateIndex}">${r.prepared?'Prepared':'Prepare'}</button></div></article>`}).join('')||'<div class="empty">No relics in the collection.</div>';const options=available.map(r=>`<option value="${r.id}">${esc(r.name)} • lvl ${r.level}</option>`).join('');$('#relicsPage').innerHTML=`${pageIntro('RELICS','Occult Collector relics')}${section('Capacity',`<div class="stat-grid">${stat('PREP',`${prep}/${lim[0]}`,'compact')}${stat('RESERVE',`${reserve}/${lim[1]}`,'compact')}${stat('TOTAL',`${sel.length}/${lim[2]}`,'compact')}${stat('RELIC DC',relicDC(),'compact')}</div>`)}${section('Collection',`<div class="inline-form"><select id="relicSelect" class="search-inline" ${sel.length>=lim[2]?'disabled':''}><option value="">Add relic…</option>${options}</select><button class="small-btn" data-add-relic ${sel.length>=lim[2]?'disabled':''}>+</button></div><div class="relic-grid top-gap">${cards}</div>`)}`}

  function inventoryItemHtml(it,index){const name=typeof it==='string'?it:it.name||'Item',rarity=typeof it==='object'?(it.rarityLabel||it.rarity||''):'';let detail='';if(typeof it==='object'&&it.source==='SRD 5.2.1'){const fields=Catalog.displayFields(it).map(([a,b])=>`<div class="formula-row"><span>${esc(a)}</span><span>${esc(b)}</span></div>`).join('');detail=`<div class="formula-list">${fields}</div><p>${esc(it.description||'')}</p><small class="muted">${esc(it.source)}</small>`}else if(typeof it==='object')detail=`<p>${esc(it.notes||'')}</p>`;return `<article class="gear-card"><button class="row-main" data-toggle-inventory="${index}"><span><strong>${esc(name)}</strong><span class="row-meta">${rarity?`<span>${esc(rarity)}</span>`:''}${typeof it==='object'&&it.category?`<span>${esc(it.category)}</span>`:''}</span></span><span>›</span></button><div class="inventory-detail" data-inventory-detail="${index}">${detail}<button class="small-btn danger top-gap" data-item-remove="${index}">Delete</button></div></article>`}
  function renderGear(){const g=state().character.gear,m=g.money||{},money=['cp','sp','gp','pp'].map(k=>`<label>${k.toUpperCase()}<input type="number" min="0" value="${Number(m[k])||0}" data-money="${k}"></label>`).join('');const items=(g.inventory||[]).map((it,i)=>({it,i})).sort((a,b)=>{const ar=Catalog?.RARITY_ORDER?.[a.it?.rarity]??99,br=Catalog?.RARITY_ORDER?.[b.it?.rarity]??99;return ar-br||String(a.it?.name||a.it).localeCompare(String(b.it?.name||b.it))}).map(x=>inventoryItemHtml(x.it,x.i)).join('')||'<div class="empty">Inventory is empty.</div>';$('#gearPage').innerHTML=`${pageIntro('GEAR','Equipment & inventory')}${section('Money',`<div class="money-grid">${money}</div>`)}${section('Inventory',`<button class="small-btn primary" data-open-catalog>+ Add from D&D SRD</button><div class="gear-grid top-gap">${items}</div><div class="catalog-attribution">${esc(Catalog?.attribution||'')}</div>`)}`}

  function renderNpcs(){const npcs=state().campaign.npcs||[],cards=npcs.map((n,i)=>`<article class="npc-card tile"><button class="npc-photo-button" data-edit-npc="${i}">${n.image?`<img class="npc-photo" src="${n.image}" alt="">`:`<div class="npc-photo npc-placeholder">♟</div>`}</button><div class="npc-info"><div class="eyebrow">${esc(n.tag||'NPC')}${n.location?` • ${esc(n.location)}`:''}</div><h3>${esc(n.name||'NPC')}</h3><p>${esc(n.notes||'')}</p><div class="npc-actions"><button class="favorite ${n.favorite?'on':''}" data-npc-favorite="${i}">★</button><button class="small-btn" data-edit-npc="${i}">Edit</button><button class="small-btn danger" data-delete-npc="${i}">Delete</button></div></div></article>`).join('')||'<div class="empty">No NPCs yet.</div>';$('#npcsPage').innerHTML=`${pageIntro('NPCs','NPC database')}${section('NPCs',`<button class="small-btn primary" data-new-npc>+ NPC</button><div class="npc-grid top-gap">${cards}</div>`)}`}

  function renderAll(){renderTop();renderCharacter();renderActions();renderSkills();renderFeatures();renderRelics();renderGear();renderNpcs();updatePageChrome()}
  function currentPageIndex(){const p=$('#pager');return Math.max(0,Math.min(PAGES.length-1,Math.round(p.scrollLeft/Math.max(1,p.clientWidth))))}
  function updatePageChrome(i=currentPageIndex()){$('#pageTitle').textContent=TITLES[i];$$('#pageDots .page-dot').forEach((d,j)=>d.classList.toggle('active',i===j))}
  function setPage(i,smooth=true){i=Math.max(0,Math.min(PAGES.length-1,i));const p=$('#pager');p.scrollTo({left:p.clientWidth*i,behavior:smooth?'smooth':'auto'});updatePageChrome(i);S.update(s=>s.ui.page=i)}
  function initDots(){$('#pageDots').innerHTML=PAGES.map((p,i)=>`<button class="page-dot" data-page-dot="${i}" aria-label="${TITLES[i]}"></button>`).join('')}
  function onPagerScroll(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const i=currentPageIndex();updatePageChrome(i);clearTimeout(savePageTimer);savePageTimer=setTimeout(()=>S.update(s=>s.ui.page=i),100)})}

  function spendCool(cost){cost=Number(cost)||0;if(cost<=0)return true;if(coolAvailable()<cost){toast('Not enough Cool Points.','warn');return false}S.update(s=>s.classes.treasureHunter.coolUsed=Math.min(coolTotal(),(Number(s.classes.treasureHunter.coolUsed)||0)+cost));return true}
  function rest(kind){if(!confirm(`${kind==='LR'?'Long':'Short'} Rest?`))return;S.update(s=>{s.classes.treasureHunter.coolUsed=0;Object.keys(s.classes.treasureHunter.featureUses||{}).forEach(id=>{const f=T.features.find(x=>x.id===id);if(f&&(kind==='LR'||f.recovery==='SR'))s.classes.treasureHunter.featureUses[id]=0});(s.classes.treasureHunter.relics||[]).forEach(x=>{if(typeof x==='string')return;const r=relicById(x.id);if(r&&(kind==='LR'||r.recovery==='SR'))x.used=0});if(kind==='LR'){s.character.hp.current=s.character.hp.max;s.character.hp.temp=0;s.character.exhaustion=Math.max(0,(Number(s.character.exhaustion)||0)-1)}});renderAll();toast(`${kind==='LR'?'Long':'Short'} Rest completed.`)}

  function openHp(){const h=state().character.hp;hpAmount=1;$('#hpCurrent').textContent=h.current;$('#hpMax').textContent=h.max;$('#hpTempRead').textContent=h.temp||0;$('#hpTemp').value=h.temp||0;$('#hpAmount').textContent=hpAmount;$('#hpDamageType').innerHTML='<option value="">No type / ignore defenses</option>'+R.DAMAGE_TYPES.map(([k,n])=>`<option value="${k}">${n}</option>`).join('');$('#hpDialog').showModal()}
  function applyHp(mode){S.update(s=>{const h=s.character.hp;if(mode==='damage'){let dmg=hpAmount,type=$('#hpDamageType').value,d=s.character.damageDefenses||{};if(type&&(d.immunities||[]).includes(type))dmg=0;else if(type&&(d.resistances||[]).includes(type))dmg=Math.floor(dmg/2);else if(type&&(d.vulnerabilities||[]).includes(type))dmg*=2;const absorb=Math.min(h.temp||0,dmg);h.temp=(h.temp||0)-absorb;h.current=Math.max(0,h.current-(dmg-absorb))}else h.current=Math.min(h.max,h.current+hpAmount);h.temp=Math.max(0,Number($('#hpTemp').value)||0)});$('#hpDialog').close();renderAll()}

  function openEdit(){const s=state();pendingPortrait=s.character.portrait||'';$('#editName').value=s.character.name||'';$('#editRace').value=s.character.race||'';$('#editLevel').innerHTML=Array.from({length:20},(_,i)=>`<option value="${i+1}" ${i+1===level()?'selected':''}>Level ${i+1}</option>`).join('');$('#editHpMax').value=s.character.hp.max;$('#editHpAuto').checked=s.character.hp.auto!==false;$('#editHpMax').disabled=$('#editHpAuto').checked;$('#editAc').value=s.character.ac;$('#editSpeed').value=s.character.speed;$('#editInitBonus').value=s.character.initiativeBonus||0;$('#abilityEditor').innerHTML=S.A.map(a=>`<label>${a}<input type="number" min="1" max="30" value="${ability(a)}" data-edit-ability="${a}"></label>`).join('');$('#editPortrait').value='';$('#portraitPreview').innerHTML=pendingPortrait?`<img src="${pendingPortrait}" alt="">`:'<span>No portrait</span>';$('#editDialog').showModal()}
  function saveEdit(ev){ev.preventDefault();const oldLevel=level(),newLevel=Math.max(1,Math.min(20,Number($('#editLevel').value)||1));if(newLevel!==oldLevel&&!confirm(`Change level from ${oldLevel} to ${newLevel}?`))return;const oldMax=state().character.hp.max,damage=Math.max(0,oldMax-state().character.hp.current),scores={};$$('[data-edit-ability]').forEach(inp=>scores[inp.dataset.editAbility]=Math.max(1,Math.min(30,Number(inp.value)||10)));const auto=$('#editHpAuto').checked,newMax=auto?T.hpMax(newLevel,mod(scores.CON)):Math.max(1,Number($('#editHpMax').value)||1);S.update(s=>{s.character.name=$('#editName').value.trim();s.character.race=$('#editRace').value.trim();s.character.level=newLevel;s.character.portrait=pendingPortrait;s.character.hp.auto=auto;s.character.hp.max=newMax;s.character.hp.current=Math.max(0,Math.min(newMax,newMax-damage));s.character.ac=Math.max(0,Number($('#editAc').value)||0);s.character.speed=Math.max(0,Number($('#editSpeed').value)||0);s.character.initiativeBonus=Number($('#editInitBonus').value)||0;s.character.abilities=scores;s.classes.treasureHunter.coolUsed=Math.min(Number(s.classes.treasureHunter.coolUsed)||0,T.coolTotal(newLevel))});S.flush();Roster?.saveCurrent();$('#editDialog').close();renderAll()}

  function openNpc(i=null){const n=i==null?{}:(state().campaign.npcs||[])[i]||{};$('#npcId').value=i==null?'':String(i);$('#npcName').value=n.name||'';$('#npcTag').value=n.tag||'';$('#npcLocation').value=n.location||'';$('#npcNotes').value=n.notes||'';$('#npcImage').value='';$('#npcDialog').showModal()}
  async function saveNpc(ev){ev.preventDefault();const idx=$('#npcId').value===''?null:Number($('#npcId').value),existing=idx==null?{}:(state().campaign.npcs||[])[idx]||{};let image=existing.image||'',file=$('#npcImage').files[0];if(file)try{image=await S.imageToThumb(file,360,.72)}catch(e){}const n={...existing,name:$('#npcName').value.trim()||'NPC',tag:$('#npcTag').value.trim(),location:$('#npcLocation').value.trim(),notes:$('#npcNotes').value.trim(),image};S.update(s=>{if(idx==null)s.campaign.npcs.push(n);else s.campaign.npcs[idx]=n});$('#npcDialog').close();renderNpcs()}

  function renderRoster(){if(!Roster)return;const active=Roster.activeId(),cards=Roster.list().map(p=>`<article class="roster-card ${p.id===active?'active':''}">${p.portrait?`<img src="${p.portrait}" alt="">`:'<div class="roster-placeholder">♟</div>'}<div><strong>${esc(p.name)}</strong><small>Level ${p.level} ${esc(p.race||'')}</small><div class="detail-actions">${p.id!==active?`<button class="small-btn primary" data-roster-switch="${p.id}">Open</button>`:'<span class="chip brass">Current</span>'}<button class="small-btn" data-roster-duplicate="${p.id}">Duplicate</button>${Roster.list().length>1?`<button class="small-btn danger" data-roster-delete="${p.id}">Delete</button>`:''}</div></div></article>`).join('');$('#rosterList').innerHTML=cards;$('#charactersDialog').showModal()}

  function openCustomAction(){['#customActionName','#customActionDamage','#customActionNotes'].forEach(s=>$(s).value='');$('#customActionType').value='Action';$('#customActionGroup').value='normal';$('#actionDialog').showModal()}
  function saveCustomAction(){const name=$('#customActionName').value.trim();if(!name)return;const action=$('#customActionType').value,group=$('#customActionGroup').value==='other'?'other':action==='Free'?'free':'custom',id=`custom-${Date.now().toString(36)}`;S.update(s=>s.character.customActions.push({id,name,action,group,source:'Custom',summary:$('#customActionNotes').value.trim(),damage:$('#customActionDamage').value.trim(),custom:true}));$('#actionDialog').close();renderActions()}

  async function openCatalog(){catalogQuery='';catalogRarity='all';catalogKind='all';$('#itemSearch').value='';$('#itemRarity').value='all';$('#itemKind').value='all';$('#itemResults').innerHTML='<div class="empty">Loading SRD 5.2.1…</div>';$('#itemDialog').showModal();await renderCatalogResults()}
  async function renderCatalogResults(){if(!Catalog)return;$('#itemResults').innerHTML='<div class="empty">Loading…</div>';try{const items=await Catalog.search(catalogQuery,{rarity:catalogRarity,kind:catalogKind,sort:'rarity'}),shown=items.slice(0,120);$('#itemResults').innerHTML=shown.map(it=>`<article class="catalog-item"><div class="catalog-item-head"><div><span class="eyebrow">${esc(it.rarity)} • ${esc(it.kind)}</span><strong>${esc(it.name)}</strong></div><button class="small-btn primary" data-catalog-add="${esc(it.id)}">Add</button></div><div class="catalog-fields">${Catalog.displayFields(it).map(([a,b])=>`<span><b>${esc(a)}</b> ${esc(b)}</span>`).join('')}</div><p>${esc(it.description||'')}</p></article>`).join('')||'<div class="empty">No items found.</div>';$('#itemResults').dataset.loadedIds=JSON.stringify(shown.map(x=>x.id));window.__V7SCatalogShown=shown}catch(e){$('#itemResults').innerHTML='<div class="empty">Could not load the SRD database. Check internet connection and try again.</div>'}}

  function renderGlobalSearch(){const q=$('#globalSearch').value.trim().toLowerCase();if(!q){$('#globalSearchResults').innerHTML='';return}const out=[];T.features.filter(f=>f.level<=level()).forEach(f=>{if(`${f.name} ${f.summary}`.toLowerCase().includes(q))out.push({type:'FEATURE',title:f.name,page:3})});T.relics.filter(r=>r.level<=level()).forEach(r=>{if(`${r.name} ${r.summary}`.toLowerCase().includes(q))out.push({type:'RELIC',title:r.name,page:4})});(state().character.gear.inventory||[]).forEach(it=>{const n=typeof it==='string'?it:it.name;if(String(n).toLowerCase().includes(q))out.push({type:'ITEM',title:n,page:5})});(state().campaign.npcs||[]).forEach(n=>{if(`${n.name} ${n.notes}`.toLowerCase().includes(q))out.push({type:'NPC',title:n.name,page:6})});$('#globalSearchResults').innerHTML=out.slice(0,30).map(r=>`<button type="button" class="search-result" data-search-jump="${r.page}"><small>${r.type}</small><strong>${esc(r.title)}</strong></button>`).join('')||'<div class="empty">Nothing found.</div>'}

  function bind(){
    initDots();$('#pager').addEventListener('scroll',onPagerScroll,{passive:true});$('#prevPage').onclick=()=>setPage(currentPageIndex()-1);$('#nextPage').onclick=()=>setPage(currentPageIndex()+1);$('#pageDots').onclick=e=>{const b=e.target.closest('[data-page-dot]');if(b)setPage(Number(b.dataset.pageDot))};
    $('#editBtn').onclick=openEdit;$('#charactersBtn').onclick=renderRoster;$('#saveEdit').onclick=saveEdit;$('#searchBtn').onclick=()=>{$('#globalSearch').value='';$('#globalSearchResults').innerHTML='';$('#searchDialog').showModal()};$('#globalSearch').oninput=renderGlobalSearch;$('#saveNpc').onclick=saveNpc;$('#saveCustomAction').onclick=saveCustomAction;
    $('#hpMinus').onclick=()=>{hpAmount=Math.max(1,hpAmount-1);$('#hpAmount').textContent=hpAmount};$('#hpPlus').onclick=()=>{hpAmount=Math.min(999,hpAmount+1);$('#hpAmount').textContent=hpAmount};$('#hpDamage').onclick=()=>applyHp('damage');$('#hpHeal').onclick=()=>applyHp('heal');
    $('#editPortrait').addEventListener('change',e=>{const f=e.target.files[0];if(f&&Cropper)Cropper.open(f,result=>{pendingPortrait=result;$('#portraitPreview').innerHTML=`<img src="${result}" alt="">`})});
    $('#itemSearch').addEventListener('input',e=>{catalogQuery=e.target.value;clearTimeout(window.__catTimer);window.__catTimer=setTimeout(renderCatalogResults,150)});$('#itemRarity').addEventListener('change',e=>{catalogRarity=e.target.value;renderCatalogResults()});$('#itemKind').addEventListener('change',e=>{catalogKind=e.target.value;renderCatalogResults()});
    document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;
      if(t.hasAttribute('data-open-hp'))return openHp();if(t.hasAttribute('data-open-edit'))return openEdit();if(t.dataset.toggleRow){document.querySelector(`[data-row="${CSS.escape(t.dataset.toggleRow)}"]`)?.classList.toggle('open');return}
      if(t.hasAttribute('data-inspiration')){S.update(s=>s.character.inspiration=!s.character.inspiration);renderAll();return}
      if(t.hasAttribute('data-short-rest'))return rest('SR');if(t.hasAttribute('data-long-rest'))return rest('LR');
      if(t.dataset.coolToggle){S.update(s=>{const u=Number(s.classes.treasureHunter.coolUsed)||0;s.classes.treasureHunter.coolUsed=Math.max(0,Math.min(coolTotal(),u+(t.dataset.coolToggle==='spend'?1:-1)))});renderCharacter();renderTop();return}
      if(t.dataset.rollCycle){const key=t.dataset.rollCycle;if(key==='initiative')S.update(s=>s.character.rollModes.initiative=cycleMode(s.character.rollModes.initiative||'normal'));else if(key.startsWith('skill:')){const n=key.slice(6);S.update(s=>{const m=s.character.rollModes.skills||(s.character.rollModes.skills={});m[n]=cycleMode(m[n]||'normal')})}renderAll();return}
      if(t.dataset.actionFilter){actionFilter=t.dataset.actionFilter;renderActions();return}if(t.hasAttribute('data-new-action'))return openCustomAction();if(t.dataset.deleteCustomAction){S.update(s=>s.character.customActions=s.character.customActions.filter(a=>a.id!==t.dataset.deleteCustomAction));renderActions();return}if(t.dataset.useAction){const a=allActions().find(x=>x.id===t.dataset.useAction);if(a&&spendCool(a.cost||0))renderAll();return}
      if(t.dataset.skillCycle){S.update(s=>{s.character.skills||(s.character.skills={});s.character.skills[t.dataset.skillCycle]=((Number(s.character.skills[t.dataset.skillCycle])||0)+1)%3});renderSkills();return}
      if(t.dataset.featureFilter){featureFilter=t.dataset.featureFilter;renderFeatures();return}if(t.dataset.favorite){S.update(s=>{const a=s.ui.favoriteFeatures||(s.ui.favoriteFeatures=[]),i=a.indexOf(t.dataset.favorite);i>=0?a.splice(i,1):a.push(t.dataset.favorite)});renderFeatures();return}
      if(t.hasAttribute('data-add-condition')){const v=$('#conditionSelect').value;if(v==='Exhaustion')S.update(s=>s.character.exhaustion=Math.max(1,s.character.exhaustion||0));else if(v)S.update(s=>{if(!s.character.conditions.includes(v))s.character.conditions.push(v)});renderCharacter();return}if(t.dataset.removeCondition){S.update(s=>s.character.conditions=s.character.conditions.filter(x=>x!==t.dataset.removeCondition));renderCharacter();return}if(t.dataset.exhaustion){S.update(s=>s.character.exhaustion=Math.max(0,Math.min(6,(Number(s.character.exhaustion)||0)+Number(t.dataset.exhaustion))));renderAll();return}if(t.hasAttribute('data-exhaustion-clear')){S.update(s=>s.character.exhaustion=0);renderAll();return}
      if(t.hasAttribute('data-add-defense')){const type=$('#defenseType').value,value=$('#defenseValue').value,key={resistance:'resistances',immunity:'immunities',vulnerability:'vulnerabilities',conditionImmunity:'conditionImmunities'}[type];S.update(s=>{const a=s.character.damageDefenses[key];if(value&&!a.includes(value))a.push(value)});renderCharacter();return}if(t.dataset.removeDefense){const [type,i]=t.dataset.removeDefense.split(':'),key={resistance:'resistances',immunity:'immunities',vulnerability:'vulnerabilities',conditionImmunity:'conditionImmunities'}[type];S.update(s=>s.character.damageDefenses[key].splice(Number(i),1));renderCharacter();return}
      if(t.hasAttribute('data-add-relic')){const id=$('#relicSelect').value;if(id&&selectedRelics().length<relicLimit()[2])S.update(s=>s.classes.treasureHunter.relics.push({id,prepared:false,used:0}));renderRelics();return}if(t.dataset.relicRemove!=null){S.update(s=>s.classes.treasureHunter.relics.splice(Number(t.dataset.relicRemove),1));renderAll();return}if(t.dataset.relicPrepared!=null){const i=Number(t.dataset.relicPrepared),r=state().classes.treasureHunter.relics[i],next=!(typeof r==='object'&&r.prepared);if(next&&selectedRelics().filter(x=>x.prepared).length>=relicLimit()[0]){toast('Prepared relic limit is full.','warn');return}S.update(s=>{let x=s.classes.treasureHunter.relics[i];if(typeof x==='string')s.classes.treasureHunter.relics[i]={id:x,prepared:next,used:0};else x.prepared=next});renderAll();return}if(t.dataset.relicCharge!=null){const i=Number(t.dataset.relicCharge),delta=t.dataset.chargeState==='full'?1:-1;S.update(s=>{let x=s.classes.treasureHunter.relics[i];if(typeof x==='string'){x={id:x,prepared:false,used:0};s.classes.treasureHunter.relics[i]=x}const max=relicMax({...relicById(x.id),...x});x.used=Math.max(0,Math.min(max,(Number(x.used)||0)+delta))});renderAll();return}
      if(t.hasAttribute('data-open-catalog'))return openCatalog();if(t.dataset.catalogAdd){const it=(window.__V7SCatalogShown||[]).find(x=>x.id===t.dataset.catalogAdd);if(it){S.update(s=>s.character.gear.inventory.push(Catalog.cloneForInventory(it)));renderGear();toast(`${it.name} added.`)}return}if(t.dataset.toggleInventory!=null){document.querySelector(`[data-inventory-detail="${t.dataset.toggleInventory}"]`)?.classList.toggle('open');return}if(t.dataset.itemRemove!=null){if(confirm('Delete this item?'))S.update(s=>s.character.gear.inventory.splice(Number(t.dataset.itemRemove),1));renderGear();return}
      if(t.hasAttribute('data-new-npc'))return openNpc();if(t.dataset.editNpc!=null)return openNpc(Number(t.dataset.editNpc));if(t.dataset.npcFavorite!=null){S.update(s=>s.campaign.npcs[Number(t.dataset.npcFavorite)].favorite=!s.campaign.npcs[Number(t.dataset.npcFavorite)].favorite);renderNpcs();return}if(t.dataset.deleteNpc!=null){if(confirm('Delete this NPC?'))S.update(s=>s.campaign.npcs.splice(Number(t.dataset.deleteNpc),1));renderNpcs();return}
      if(t.dataset.rosterSwitch)return Roster.switchTo(t.dataset.rosterSwitch);if(t.dataset.rosterDuplicate)return Roster.duplicate(t.dataset.rosterDuplicate);if(t.dataset.rosterDelete){if(confirm('Delete this character?'))Roster.remove(t.dataset.rosterDelete);return}if(t.hasAttribute('data-roster-new')){Roster.create();return}
      if(t.dataset.searchJump!=null){$('#searchDialog').close();setPage(Number(t.dataset.searchJump));return}
    });
    document.addEventListener('change',e=>{if(e.target.id==='defenseType')$('#defenseValue').innerHTML=defenseValueOptions(e.target.value);if(e.target.id==='editHpAuto')$('#editHpMax').disabled=e.target.checked;if(e.target.dataset.featureChoice){const key=e.target.dataset.featureChoice,i=Number(e.target.dataset.choiceIndex)||0,val=e.target.value;S.update(s=>{const th=s.classes.treasureHunter;if(key==='expertise')th.expertise=val;else{if(!Array.isArray(th[key]))th[key]=[];th[key][i]=val}});renderSkills()}});
    document.addEventListener('input',e=>{if(e.target.id==='featureSearch'){featureSearch=e.target.value;renderFeatures();$('#featureSearch')?.focus()}if(e.target.dataset.money){const k=e.target.dataset.money;S.update(s=>s.character.gear.money[k]=Math.max(0,Number(e.target.value)||0))}});
  }

  document.addEventListener('DOMContentLoaded',()=>{bind();renderAll();requestAnimationFrame(()=>setPage(Number(state().ui.page)||0,false))});
})();