(function(){
  const S=window.V7SStateV7s,Roster=window.V7SRoster,O=window.V7SCampaignOrigin;if(!S)return;
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const AB={Strength:'STR',Dexterity:'DEX',Constitution:'CON',Intelligence:'INT',Wisdom:'WIS',Charisma:'CHA',STR:'STR',DEX:'DEX',CON:'CON',INT:'INT',WIS:'WIS',CHA:'CHA'};
  let pending=null,report=[];
  function toast(m,t='success'){const h=$('#toastHost');if(!h)return;const e=document.createElement('div');e.className=`toast ${t}`;e.textContent=m;h.appendChild(e);setTimeout(()=>e.remove(),2400)}
  function inject(){if(!$('#importDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="importDialog" class="sheet-dialog import-dialog"><form method="dialog"><div class="dialog-head"><strong>Import Character Data</strong><button value="cancel" class="icon-btn">×</button></div><div class="import-source-row"><label class="file-btn">Choose JSON file<input id="importFile" type="file" accept="application/json,.json" hidden></label><span>or paste JSON below</span></div><textarea id="importText" rows="12" spellcheck="false" placeholder='{"name":"...","level":5,...}'></textarea><div id="importReport" class="import-report">Native V7s, roster JSON, Character Craft JSON, and the simple sheet format are supported.</div><menu><button type="button" class="ghost" id="copyTemplate">Copy template</button><button type="button" class="primary" id="previewImport">Check import</button><button type="button" class="primary" id="applyImport" disabled>Import</button></menu></form></dialog>`)}
  function patchCharacters(){const d=$('#charactersDialog form');if(!d||d.querySelector('.import-toolbar'))return;const newBtn=d.querySelector('[data-roster-new]');const bar=document.createElement('div');bar.className='import-toolbar';bar.innerHTML='<button type="button" class="small-btn" data-import-open>⇩ Import JSON</button><button type="button" class="small-btn" data-export-character>⇧ Export Character</button><button type="button" class="small-btn" data-export-roster>Export All</button>';newBtn?.after(bar)}
  function template(){return {format:'v7s-simple-character',name:'Example Character',level:1,species:'City Goblin',background:'Lukyho univerzální background',abilities:{STR:10,DEX:10,CON:10,INT:10,WIS:10,CHA:10},hp:{current:10,max:10,temp:0},skills:{Acrobatics:1},gear:{weapons:[],inventory:[]},bio:{alignment:'',appearance:'',backstory:''},treasureHunter:{classSkills:[],ancientLanguages:[],vehicles:[],expertise:'',weaponMasteries:[],relics:[]}}}
  function download(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
  function parseBackgroundSelections(desc=''){const out={skills:[],tool:'',secondary:'',abilityBonuses:{}};const sm=desc.match(/Skills?:\s*([^\n.]+)/i);if(sm)out.skills=sm[1].split(/,| and /i).map(x=>x.trim()).filter(Boolean).slice(0,2);const tm=desc.match(/Tool:\s*([^\n.]+)/i);if(tm)out.tool=tm[1].trim();const vm=desc.match(/(?:Vehicle|Instrument|Game(?: Set)?):\s*([^\n.]+)/i);if(vm)out.secondary=vm[1].trim();const am=desc.match(/Ability Scores?:\s*([^\n.]+)/i);if(am){for(const m of am[1].matchAll(/\+(\d)\s+(Strength|Dexterity|Constitution|Intelligence|Wisdom|Charisma)/gi)){out.abilityBonuses[AB[m[2][0].toUpperCase()+m[2].slice(1).toLowerCase()]]=Number(m[1])}}return out}
  function collectGear(p){const src=p.inventory||p.items||p.equipment;if(!Array.isArray(src))return[];return src.map((x,i)=>typeof x==='string'?{uid:`import-${Date.now()}-${i}`,name:x,quantity:1,location:'backpack',modifiers:[]}:{uid:x.uid||`import-${Date.now()}-${i}`,name:x.name||x.itemName||'Imported item',quantity:Number(x.quantity)||1,location:x.location||'backpack',weight:Number(x.weight)||undefined,description:x.description||'',raw:x.raw||x,modifiers:Array.isArray(x.modifiers)?x.modifiers:[]})}
  function inferLevel(p){for(const v of [p.level,p.characterLevel,p.levelNumber]){const n=Number(v);if(n>=1&&n<=20)return n}const classes=Array.isArray(p.class)?p.class:[];for(const c of classes){const n=Number(c.level);if(n>=1&&n<=20)return n;const keys=Object.keys(c.hpGainedPerLevel||{}).map(Number).filter(Number.isFinite);if(keys.length)return Math.max(...keys)}return 1}
  function characterCraft(p){const s=S.fresh(),c=s.character,th=s.classes.treasureHunter;report=[];c.name=p.name||'Imported Character';report.push(`Name: ${c.name}`);c.level=inferLevel(p);report.push(`Level: ${c.level}`);const attrs=p.attributes||p.abilities||{};Object.entries(attrs).forEach(([k,v])=>{const a=AB[k];if(a&&Number.isFinite(Number(v)))c.abilities[a]=Number(v)});report.push('Ability scores');
    const sp=typeof p.species==='string'?{name:p.species}:p.species||{};if(sp.name){c.race=sp.name;c.origin={species:sp.name,speciesChoices:{skills:Array.isArray(sp.skillProficiencies)?sp.skillProficiencies.slice(0,2):[],simpleWeapon:Array.isArray(sp.proficiency)?sp.proficiency[0]||'':''},background:{}};const speed=parseInt(sp.speed,10);if(speed)c.speed=speed;if(Array.isArray(sp.skillProficiencies))sp.skillProficiencies.forEach(x=>c.skills[x]=1);c.proficiencies.weapons.push(...(sp.proficiency||[]).filter(x=>x&&!/choose/i.test(x)));if(Number(sp.darkvisionRange))c.proficiencies.senses.push(`Darkvision ${Number(sp.darkvisionRange)} ft.`);report.push(`Species: ${sp.name}`)}
    const bg=typeof p.background==='string'?{name:p.background,description:''}:p.background||{};if(bg.name){c.background=bg.name;const sel=parseBackgroundSelections(bg.description||''),feat=(bg.features?.[0]?.name)||String(bg.name).split(' - ').pop();c.origin||(c.origin={species:c.race,speciesChoices:{skills:[],simpleWeapon:''}});c.origin.background={name:'Lukyho univerzální background',skills:sel.skills,tool:sel.tool,secondary:sel.secondary,feat:Object.keys(O?.BACKGROUND?.feats||{}).includes(feat)?feat:'',abilityMode:Object.values(sel.abilityBonuses).filter(x=>x===2).length?'+2/+1':'+1/+1/+1',abilityChoices:Object.keys(sel.abilityBonuses),appliedBonuses:sel.abilityBonuses,resilientAbility:'',skilledChoices:[]};sel.skills.forEach(x=>c.skills[x]=1);if(sel.tool)c.proficiencies.tools.push(sel.tool);if(sel.secondary)c.proficiencies.tools.push(sel.secondary);report.push(`Background: ${bg.name}`)}
    const hpBy=Array.isArray(p.class)?p.class[0]?.hpGainedPerLevel:null;if(hpBy&&typeof hpBy==='object'){const total=Object.values(hpBy).reduce((n,v)=>n+(Number(v)||0),0);if(total>0)c.hp={current:total,max:total,temp:0,auto:false}}else if(p.hp){c.hp.current=Number(p.hp.current??p.hp)||c.hp.current;c.hp.max=Number(p.hp.max??p.maxHp)||c.hp.max;c.hp.temp=Number(p.hp.temp)||0}if(typeof p.image==='string')c.portrait=p.image;
    c.gear.inventory=collectGear(p);if(c.gear.inventory.length)report.push(`${c.gear.inventory.length} inventory items`);if(p.bio&&typeof p.bio==='object')c.bio={...p.bio};
    report.push('Class-specific free-choice selections are imported only when the JSON contains explicit selected values; option catalogs are not mistaken for selections.');return s}
  function simple(p){const s=S.fresh(),c=s.character,th=s.classes.treasureHunter;report=[];c.name=p.name||c.name;c.level=Math.max(1,Math.min(20,Number(p.level)||1));c.race=p.species||p.race||'';c.background=p.background||'';Object.entries(p.abilities||{}).forEach(([k,v])=>{const a=AB[k];if(a)c.abilities[a]=Number(v)||10});if(p.hp&&typeof p.hp==='object')c.hp={...c.hp,...p.hp};if(p.skills&&typeof p.skills==='object')c.skills={...p.skills};if(p.gear&&typeof p.gear==='object')c.gear={...c.gear,...p.gear};if(p.bio&&typeof p.bio==='object')c.bio={...p.bio};if(p.treasureHunter&&typeof p.treasureHunter==='object')Object.assign(th,p.treasureHunter);report.push('Simple V7s character data');return s}
  function classify(p){if(p&&Array.isArray(p.profiles))return{kind:'roster',data:p};if(p?.schemaVersion&&p?.character&&p?.classes)return{kind:'native',data:p};if(p?.name&&(p.species||p.attributes)&&(Array.isArray(p.class)||p.background))return{kind:'character-craft',data:characterCraft(p)};if(p?.format==='v7s-simple-character'||p?.name||p?.abilities)return{kind:'simple',data:simple(p)};throw new Error('JSON format not recognized')}
  function preview(text){try{const p=JSON.parse(text),x=classify(p);pending=x;$('#applyImport').disabled=false;$('#importReport').innerHTML=`<b>${esc(x.kind.toUpperCase())}</b>${report.length?`<ul>${report.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Valid V7s data detected.</p>'}`;return true}catch(e){pending=null;$('#applyImport').disabled=true;$('#importReport').innerHTML=`<b>Cannot import</b><p>${esc(e.message)}</p>`;return false}}
  function apply(){if(!pending)return;if(pending.kind==='roster'){if(!Roster?.importAll(pending.data)){toast('Roster import failed','warn');return}return}if(pending.kind==='native'){S.replace(pending.data);S.flush()}else{const currentCampaign=S.clone(S.get().campaign||{});pending.data.campaign=currentCampaign;S.replace(pending.data);S.flush()}$('#importDialog').close();toast('Character imported.','success');window.dispatchEvent(new CustomEvent('v7s:state-changed'));setTimeout(()=>location.reload(),180)}
  document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.hasAttribute('data-import-open')){inject();pending=null;$('#importText').value='';$('#applyImport').disabled=true;$('#importReport').textContent='Paste JSON or choose a file.';$('#importDialog').showModal()}else if(t.hasAttribute('data-export-character'))download(`${(S.get().character.name||'character').replace(/[^a-z0-9_-]+/gi,'_')}.json`,S.get())else if(t.hasAttribute('data-export-roster'))download('character-sheet-roster.json',Roster?.exportAll?Roster.exportAll():{current:S.get()});else if(t.id==='previewImport')preview($('#importText').value);else if(t.id==='applyImport')apply();else if(t.id==='copyTemplate'){navigator.clipboard?.writeText(JSON.stringify(template(),null,2)).then(()=>toast('Import template copied.')).catch(()=>{$('#importText').value=JSON.stringify(template(),null,2)})}},true);
  document.addEventListener('change',e=>{if(e.target.id==='importFile'){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{$('#importText').value=String(r.result||'');preview($('#importText').value)};r.readAsText(f)}},true);
  document.addEventListener('DOMContentLoaded',()=>{inject();patchCharacters()});S.subscribe(()=>setTimeout(patchCharacters,0));setTimeout(()=>{inject();patchCharacters()},160);
})();
