(function(){
  const F=(id,level,name,fullText,opts={})=>({id,level,name,summary:String(fullText||'').split('\n')[0],fullText,action:'Passive',cost:0,kind:'class',...opts});

  const features=[
    F('ancient-languages',1,'Starověké jazyky',`Znáš tři starověké jazyky z následujícího seznamu: latina, starý keltský jazyk, starý germánský jazyk, stará řečtina, egyptština, hebrejština, arabština, perština, akkadština (včetně babylonštiny a asyrštiny), sanskrt, mandarínština, nahuatl, mayské jazyky a kečuánština.\n\nMáš Výhodu na ověření Historie týkající se kultury, jejíž starověký jazyk znáš. Například znalost kečuánštiny ti dává Výhodu na ověření Historie týkající se Incké říše, její kultury, zvyků a artefaktů.`),
    F('drivers-license',1,'Řidičský průkaz',`Získáš zdatnost se dvěma druhy dopravních prostředků podle své volby.`),
    F('specialized-expertise',1,'Specializovaná odbornost',`Vyber jednu dovednost, se kterou jsi zdatný. V této dovednosti získáš Odbornost.`),
    F('conversational-tourist',1,'Konverzační turista',`Pomocí gest, výrazů a několika univerzálních slov dokážeš předat jednoduchou myšlenku tvorovi s Inteligencí 8 nebo vyšší, se kterým nesdílíš žádný jazyk, a stejně tak porozumět jeho jednoduché odpovědi. Pro složitější komunikaci může PJ požadovat ověření Charismatu.`),
    F('born-stunt-performer',1,'Rozený kaskadér',`Při určování délky a výšky svých skoků můžeš použít hodnotu Obratnosti místo Síly. Při ověření vlastnosti souvisejícím se skákáním, šplháním nebo udržením rovnováhy můžeš použít Obratnost místo Síly.\n\nRozběhový skok do dálky: až počet stop rovný tvé Obratnosti. Skok do dálky z místa: polovina této vzdálenosti. Rozběhový skok do výšky: 3 + modifikátor Obratnosti stop, minimálně 0. Skok do výšky z místa: polovina této vzdálenosti.`),
    F('cool-die',1,'Cool die',`Některé schopnosti Lovce pokladů používají Cool die. Na 1.–4. úrovni má velikost d6, na 5.–9. úrovni d8, na 10.–15. úrovni d10 a na 16.–20. úrovni d12.`),
    F('whip-master',1,'Mistr biče',`Bič používáš jako zbraň i všestranný dobrodružný nástroj. Kostka zranění tvého biče je d6. Kdykoli můžeš provést útok, můžeš jej provést bičem. Kdykoli bys provedl útok bičem, můžeš jej místo toho nahradit jedním z triků této schopnosti.\n\nBič si zachovává všechny své ostatní vlastnosti a můžeš používat jeho vlastnost Mistrovství. Pouhé držení biče ti nedává další útok.`),
    F('object-manipulation',1,'Manipulace s předmětem',`Útok bičem můžeš nahradit přitažením předmětu do 15 stop od sebe.\n\nNehlídaný Drobný předmět přitáhneš do volné ruky, ke svým nohám nebo až o 15 stop směrem k sobě. Tento trik nezpůsobuje zranění a nefunguje na předměty pevně připevněné k tělu nebo magicky spojené se svým držitelem.`,{action:'Other'}),
    F('swing',1,'Zhoupnutí',`Místo Indyho skluzu můžeš Bonusovou akcí zachytit bičem nebo lanem vhodný nehybný či pohybující se objekt, který vidíš do 15 stop od sebe, a zhoupnout se z něj nebo se nechat táhnout. Tato Bonusová akce se počítá jako tvé použití Indyho skluzu v tomto kole.\n\nPokud k pohybu při zhoupnutí nebo tažení dochází během tvého tahu a máš schopnost Útočný skluz, můžeš pohyb přerušovat útoky provedenými v rámci akce Útok. Pohyb mimo tvůj tah ti žádné další útoky neposkytuje.\n\nPříležitostné útoky vyvolané tímto pohybem mají proti tobě Nevýhodu. Bič nebo lano musíš držet alespoň v jedné ruce. V obtížné situaci může PJ vyžadovat ověření Obratnosti (Akrobacie) nebo hod na útok bičem proti DC, které určí.\n\nPři zachycení nehybného objektu se bezpečně pohneš přímou čarou až do vzdálenosti rovné dvojnásobku vzdálenosti mezi tebou a objektem. Tento pohyb nespotřebovává tvou Rychlost.`,{action:'Bonus Action'}),
    F('towing',1,'Tažení',`Když vhodný pohybující se objekt, například vůz, opouští tvůj dosah 15 stop a v tomto kole jsi ještě nepoužil Indyho skluz, můžeš Reakcí objekt zachytit bičem nebo lanem a nechat se jím táhnout. Tato Reakce se počítá jako tvé použití Indyho skluzu v tomto kole.\n\nDokud jsi připojen, pohybuješ se s tažným objektem pokaždé, když se pohne. Připojení trvá do konce tvého příštího tahu. Během tohoto tahu jej můžeš Bonusovou akcí prodloužit do konce následujícího tahu; tato Bonusová akce se počítá jako použití Indyho skluzu. Takto můžeš tažení prodlužovat opakovaně.\n\nPokud objekt prudce zatočí nebo výrazně změní směr, musíš uspět v záchranném hodu na Obratnost proti DC určenému PJ. Při neúspěchu se pustíš. Automaticky se také pustíš, pokud během tažení použiješ svou Rychlost k pohybu, pustíš bič nebo lano nebo získáš stav Vyřazený.`,{action:'Reaction'}),
    F('weapon-mastery',1,'Mistrovství zbraní',`Vyber dva druhy zbraní, se kterými jsi zdatný. Můžeš používat jejich vlastnosti Mistrovství. Kdykoli dokončíš Dlouhý odpočinek, můžeš jednu vybranou zbraň nahradit jinou.`),
    F('indy-slide',1,'Indyho skluz',`Bonusovou akcí se jednou za kolo pohneš až 15 stop přímou čarou. Tento pohyb nespotřebovává tvou Rychlost.\n\n• Během skluzu nemůžeš měnit směr.\n• Můžeš projít prostorem tvora své velikosti nebo většího, pokud je pod ním nebo kolem něj fyzicky dost místa.\n• Příležitostné útoky vyvolané tímto pohybem mají proti tobě Nevýhodu.\n• Po dokončení skluzu získáš stav Na zemi.\n• Dokud nezískáš Útočný skluz, během tohoto pohybu nemůžeš útočit.\n• Skluz musí skončit v platném neobsazeném prostoru, který můžeš zaujmout.\n• Indyho skluz nemůžeš použít, pokud je tvá Rychlost 0.`,{action:'Bonus Action'}),
    F('indy-get-up',1,'Indyho vstávání',`Když máš stav Na zemi, můžeš Bonusovou akcí vstát bez spotřeby Rychlosti. Pokud to okolnosti dovolují, můžeš tuto schopnost použít také ke vstání z postele, sedadla nebo podobné polohy.`,{action:'Bonus Action'}),

    F('cool-points',2,'Body coolu',`Tvou odvahu, improvizaci a neuvěřitelné štěstí představují Body coolu. Jejich celkový počet se rovná tvé úrovni Lovce pokladů.\n\nVšechny utracené Body coolu obnovíš po Krátkém nebo Dlouhém odpočinku.`,{action:'Resource'}),
    F('narrow-escape',2,'Únik o vlásek',`Když tě zasáhne hod na útok, ale ještě před vyhodnocením jeho zranění, můžeš použít Reakci a utratit 1 Bod coolu. Získáš Dočasné životy rovné jednomu hodu Cool die + tvé úrovni Lovce pokladů + Bonus zdatnosti.\n\nPo vyhodnocení útoku se můžeš okamžitě pohnout až o 5 stop. Tento pohyb nevyvolává Příležitostné útoky.`,{action:'Reaction',cost:1}),
    F('snatch-item',2,'Vytržení předmětu',`Když zasáhneš tvora útokem bičem, můžeš utratit 1 Bod coolu a zvolit jeden předmět, který cíl drží. Cíl musí uspět v záchranném hodu na Sílu proti DC biče. Pokud předmět drží dvěma rukama, má na tento záchranný hod Výhodu.\n\nPři neúspěchu mu předmět vytrhneš a přitáhneš jej do své volné ruky nebo do prostoru u svých nohou. Útok způsobí své běžné zranění bez ohledu na výsledek záchranného hodu. Schopnost nefunguje na nošený, pevně připevněný nebo magicky spojený předmět.`,{action:'Other',cost:1}),
    F('attack-slide',2,'Útočný skluz',`Při použití Indyho skluzu můžeš jeho pohyb přerušovat útoky, které provádíš v rámci akce Útok, a jednotlivé útoky můžeš provést v různých bodech skluzu.\n\nKdyž skluz zahájíš, můžeš utratit 1 Bod coolu a zvolit Přesný skluz nebo Útok v linii. Během jednoho skluzu můžeš běžně použít jen jedno z těchto vylepšení.`,{action:'Other',cost:1}),
    F('precision-slide',2,'Přesný skluz',`Během Přesného skluzu můžeš provádět útoky zblízka i na dálku, včetně útoků střelnými zbraněmi.\n\nJednou během skluzu můžeš před hodem na útok zbraní prohlásit útok za přesný. Hod má Výhodu. Při zásahu způsobí útok navíc zranění rovné jednomu hodu Cool die; typ zranění je stejný jako u zbraně.\n\nTvor zasažený tímto útokem proti tobě nemůže do konce tvého tahu provádět Příležitostné útoky.`,{action:'Other'}),
    F('line-attack',2,'Útok v linii',`Když během Útočného skluzu provádíš akci Útok, můžeš jeden ze svých útoků nahradit Útokem v linii. Tuto možnost můžeš použít jen tehdy, pokud můžeš zacílit alespoň dva různé tvory.\n\nZvol počet tvorů až do výše svého modifikátoru Obratnosti, minimálně dva. Každý zvolený tvor musí být v dosahu zbraně na blízko, kterou držíš, v některém okamžiku skluzu. Proti každému proveď samostatný hod na útok a vyhodnoť je v pořadí, v jakém kolem tvorů projíždíš. Každého můžeš zacílit jen jednou.\n\nPrvní zásah způsobí běžné zranění zbraně včetně modifikátoru vlastnosti a Mistrovství. Každý další zásah způsobí pouze jeden hod Kostkou zranění zbraně. Nepřidáváš modifikátor vlastnosti a nelze použít Mistrovství, dodatečné zranění ani jiný efekt spouštěný zásahem.\n\nŽádný tvor zasažený tímto útokem proti tobě nemůže do konce tvého tahu provádět Příležitostné útoky.`,{action:'Other'}),
    F('when-going-tough',2,'Když jde do tuhého',`Když házíš Iniciativu, můžeš obnovit všechny utracené Body coolu. Současně hoď Cool die a obnov si tolik Životů, kolik padlo. Body coolu nelze obnovit nad maximum pro tvou úroveň.\n\nJakmile tuto schopnost použiješ, nemůžeš ji použít znovu, dokud nedokončíš Dlouhý odpočinek.`,{action:'Other',uses:1,recovery:'LR'}),

    F('treasure-hunter-subclass',3,'Archetyp Lovce pokladů',`Na 3. úrovni získáš archetyp Lovce pokladů. Tento sheet používá archetyp Okultní sběratel. Další schopnosti archetypu získáváš na 6., 10. a 14. úrovni.`),
    F('adventurers-rope',3,'Dobrodružné lano',`Lano je jeden z nejdůležitějších nástrojů dobrodruha. Naučil ses jej používat nejen ke šplhání a slaňování, ale také k chytání nepřátel, jejich přitahování a překonávání překážek.\n\nZ vhodného lana můžeš vytvořit smyčku. K jejímu použití potřebuješ alespoň jednu volnou ruku. Lano není Zbraň a nemá vlastnost Mistrovství. DC lana = 8 + Bonus zdatnosti + modifikátor Obratnosti.`),
    F('rope-snare',3,'Laso',`Kdykoli provádíš akci Útok, můžeš jeden ze svých útoků nahradit hodem lana na Velkého nebo menšího tvora do 15 stop.\n\nCíl musí uspět v záchranném hodu na Obratnost proti DC lana. Při neúspěchu získá stav Chycený, ty jsi držící tvor a držíš konec lana.\n\nDokud držíš konec lana alespoň v jedné ruce, můžeš se pohybovat normálně, ale nesmíš se vzdálit více než 20 stop od tvora chyceného lanem. Pokud lano pustíš, je zničeno, získáš stav Vyřazený nebo se vzdálíš více než 20 stop, stav Chycený okamžitě končí.\n\nTvor může Akcí provést ověření Síly (Atletika) nebo Obratnosti (Akrobacie) proti DC lana; při úspěchu stav Chycený skončí.`,{action:'Other'}),
    F('rope-pull',3,'Přitažení lanem',`Jednou během každého svého tahu můžeš bez použití akce přitáhnout tvora Chyceného tvým lanem.\n\nJe-li tvor Velký nebo menší, přitáhneš jej až o 10 stop k sobě. Je-li větší, místo toho se ty pohneš až o 10 stop směrem k němu.`,{action:'Free'}),
    F('rope-takedown',3,'Stržení lanem',`Když je tvor Chycený tvým lanem, můžeš jeden ze svých útoků nahradit pokusem jej strhnout. Cíl musí uspět v záchranném hodu na Sílu proti DC lana, jinak získá stav Na zemi.`,{action:'Other'}),
    F('quick-rope',3,'Pohotové lano',`Když se Velký nebo menší tvor, kterého vidíš do 15 stop, chystá opustit tento dosah pomocí svého pohybu, Akce, Bonusové akce nebo Reakce, můžeš těsně před opuštěním dosahu použít Reakci. Musíš mít jednu ruku volnou a lanem už nesmíš držet jiného tvora.\n\nCíl musí uspět v záchranném hodu na Obratnost proti DC lana. Při neúspěchu získá stav Chycený, ty jsi držící tvor, jeho pohyb okamžitě končí a zůstane v prostoru, ve kterém Reakci spustil. Při úspěchu se nic nestane.\n\nTuto Reakci nespouští tvor, který použil Odpoutání, teleportoval se nebo byl přesunut způsobem, který nevyvolává Příležitostné útoky.`,{action:'Reaction'}),

    F('initial-collection',3,'Počáteční sbírka',`Získáš čtyři relikvie podle své volby ze seznamu Okultního sběratele. Musíš splňovat jejich požadavky na úroveň. Dvě jsou připravené a ostatní tvoří rezervu.\n\nRelikvie mohou pocházet z dřívějších výprav, od mentora nebo z úvodního dobrodružství. PJ může jednu nahradit příběhovým předmětem se stejnými mechanickými vlastnostmi nebo do sbírky přidat unikátní relikvie jako odměny.\n\nKdykoli získáš úroveň Lovce pokladů, můžeš jednu relikvii získanou z tohoto archetypu nahradit jinou, pro kterou splňuješ požadavky.`,{kind:'subclass'}),
    F('prepared-relics-reserve',3,'Připravené relikvie a rezerva',`Relikvie, které můžeš právě používat, jsou tvé připravené relikvie. Ostatní relikvie získané z tohoto archetypu tvoří rezervu.`,{kind:'subclass'}),
    F('bag-full-secrets',3,'Brašna plná tajemství',`Tato nenápadná cestovní brašna slouží jako běžné zavazadlo, ale zároveň obsahuje průchod do malého extradimenzionálního úložného prostoru. Do něj lze vložit pouze relikvie získané z tohoto archetypu. Průchod se magicky přizpůsobí tvaru a velikosti každé relikvie, takže se do brašny vejde bez ohledu na rozměry. Relikvie uvnitř nic neváží a jejich vlastnosti nelze používat.\n\nPřipravené relikvie jsou fyzicky uloženy v brašně, pokud je právě nedržíš, nenosíš nebo jsi je někam neumístil. Když do brašny sáhneš pro konkrétní připravenou relikvii, vždy ji okamžitě najdeš. Relikvie v rezervě zůstávají v extradimenzionálním prostoru nedostupné a nelze je vyjmout, dokud je nepřipravíš.`,{kind:'subclass'}),
    F('preparing-relics',3,'Příprava relikvií',`Kdykoli dokončíš Dlouhý odpočinek, můžeš změnit své připravené relikvie. Relikvie, které už nejsou připravené, zmizí do brašny bez ohledu na to, kde právě jsou. Nově připravené relikvie zůstanou fyzicky uložené v brašně, odkud je můžeš běžně vyjmout. Tato změna žádnou relikvii neaktivuje ani neobnovuje její náboje či omezená použití.`,{kind:'subclass'}),
    F('handling-relics',3,'Manipulace s relikviemi',`Jednou během každého svého tahu, pokud máš Brašnu plnou tajemství u sebe, můžeš bez použití akce vyjmout jednu relikvii z brašny do volné ruky nebo uložit do brašny jednu relikvii ve svém dosahu. Každá další taková interakce ve stejném tahu vyžaduje akci Použití předmětu.`,{kind:'subclass',action:'Free'}),
    F('using-relics',3,'Používání relikvií',`Připravenou relikvii můžeš použít jen tehdy, když je mimo brašnu. Pokud její popis neříká jinak, při aktivaci ji musíš držet nebo nosit, je-li určena k nošení. Jako součást aktivace relikvie s trvajícím efektem ji můžeš položit do neobsazeného prostoru ve svém dosahu.\n\nRelikvie potřebná k Reakci musí být mimo brašnu ještě před spuštěním Reakce. Popis každé relikvie určuje její použití a další omezení. Za tah můžeš aktivovat pouze jednu relikvii. Utracení náboje nebo omezeného použití se vždy počítá jako aktivace, pokud popis neříká jinak. Pasivní vlastnosti se za aktivaci nepočítají.\n\nPokud relikvii vrátíš do brašny, okamžitě skončí každý efekt, který vyžaduje její fyzickou přítomnost. Ostatní efekty pokračují po dobu uvedenou v jejich popisu.`,{kind:'subclass'}),
    F('magical-bond',3,'Magické pouto',`Relikvie získané z tohoto archetypu jsou magicky spojeny pouze s tebou. Jiný tvor nemůže aktivovat jejich vlastnosti, utrácet jejich náboje ani získávat jejich pasivní výhody, i když relikvii drží nebo nosí. Může však být cílem nebo jinak ovlivněn efektem, který relikvií vytvoříš.\n\nTyto relikvie nevyžadují Sladění a nezabírají pozici Sladění, pokud jejich popis neříká jinak. Brašna plná tajemství je také magický předmět spojený s tebou a vždy znáš její směr a vzdálenost.`,{kind:'subclass'}),
    F('bags-protection',3,'Ochrana brašny',`Když jiný tvor sáhne do brašny bez tvého svolení nebo pokynu, musí provést záchranný hod na Moudrost proti DC rovnému 8 + Bonus zdatnosti + modifikátor Inteligence.\n\nPři neúspěchu utrpí Silové zranění rovné počtu d6 odpovídajícímu tvé úrovni Lovce pokladů + tvé úrovni Lovce pokladů, je odhozen 10 stop od brašny a nic nevytáhne. Při úspěchu utrpí poloviční zranění, není odhozen a může zamýšlenou interakci dokončit. DC záchrany relikvií = 8 + Bonus zdatnosti + modifikátor Inteligence.`,{kind:'subclass'}),
    F('expert-identification',3,'Odborná identifikace',`Po 1 hodině soustředěného zkoumání magického předmětu zjistíš jeho běžné vlastnosti, způsob aktivace a případný požadavek na Sladění. Kletbu automaticky neodhalíš, ale můžeš provést ověření Inteligence (Arkány, Historie nebo Náboženství) proti DC určenému PJ. Při úspěchu zjistíš, že je předmět prokletý, ale ne přesnou povahu kletby.`,{kind:'subclass'}),
    F('know-not-to-touch',3,'Vím, čeho se nedotýkat',`Máš Výhodu na záchranné hody způsobené prokletými magickými předměty.`,{kind:'subclass'}),

    F('asi-4',4,'Zvýšení hodnot vlastností',`Získáš feat Zvýšení hodnot vlastností nebo jiný feat, pro který splňuješ podmínky.`),
    F('catch-a-fall',4,'Zachycení pádu',`Když ty nebo jiný tvor do 15 stop začne padat, můžeš Reakcí zkusit pád zastavit. Můžeš použít volnou ruku do 5 stop nebo bič či lano do 15 stop. Proveď ověření Obratnosti (Akrobacie) proti DC určenému PJ.\n\nPokud chytáš jiného tvora, musíš navíc utratit 1 Bod coolu. Při úspěchu pád zastavíš a zachycený tvor zůstane viset 5 stop pod tebou při chycení rukou nebo 15 stop pod tebou při chycení bičem či lanem. Pokud je tvor alespoň o jednu velikost větší než ty, může tě stáhnout s sebou a PJ může vyžadovat ověření Síly (Atletika).`,{action:'Reaction',cost:1}),
    F('extra-attack',5,'Útok navíc',`Kdykoli během svého tahu provádíš akci Útok, můžeš zaútočit dvakrát místo jednou. Jednotlivé útoky můžeš nahrazovat triky s bičem nebo lanem, pokud splňuješ jejich podmínky.`,{action:'Action'}),
    F('eye-for-traps',5,'Oko na pasti',`Kdykoli provádíš ověření vlastnosti k nalezení, odhalení nebo zneškodnění pasti nebo záchranný hod k vyhnutí se jejím účinkům, můžeš k hodu přidat svůj modifikátor Inteligence, pokud už jej hod neobsahuje. Jakmile past objevíš, určíš její pravděpodobný spouštěč a základní funkci.`),
    F('seasoned-traveler',6,'Zkušený cestovatel',`Získáš Rychlost šplhání a Rychlost plavání rovnou své Rychlosti.`),
    F('relic-connoisseur',6,'Znalec relikvií',`Získáš dvě další relikvie podle své volby. Současně můžeš mít tři připravené relikvie a tři relikvie v rezervě.`,{kind:'subclass'}),
    F('another-piece-collection',6,'Další kousek ze sbírky',`Akcí můžeš nahradit jednu připravenou relikvii relikvií ze své rezervy, kterou máš u sebe. Výměna relikvii neaktivuje ani neobnovuje její náboje či omezená použití.`,{kind:'subclass',action:'Action'}),
    F('intelligent-use',6,'Inteligentní použití',`Pokud magický předmět používá tvou sesílací vlastnost, můžeš pro něj použít Inteligenci. Jeho modifikátor útoku je modifikátor Inteligence + Bonus zdatnosti a jeho DC záchrany je 8 + modifikátor Inteligence + Bonus zdatnosti.`,{kind:'subclass'}),
    F('familiar-premonition',6,'Známá předtucha',`Jednou za Dlouhý odpočinek můžeš bez použití akce aktivně vycítit přítomnost prokletých předmětů do 5 stop od sebe. Pokud se v tomto dosahu nějaké nacházejí, víš, které předměty jsou prokleté.`,{kind:'subclass',action:'Free',uses:1,recovery:'LR'}),
    F('evasion',7,'Úhyb',`Když jsi vystaven efektu, který ti dovoluje záchranný hod na Obratnost pro poloviční zranění, při úspěchu neutrpíš žádné zranění a při neúspěchu jen polovinu. Tuto schopnost nemůžeš použít, pokud máš stav Vyřazený.`),
    F('improved-slide',7,'Vylepšený skluz',`Maximální vzdálenost Indyho skluzu se zvýší na 20 stop. Pokud po skluzu během stejného tahu vstáváš běžným způsobem, stojí tě vstání pouze 10 stop Rychlosti místo poloviny Rychlosti, pokud je to pro tebe výhodnější.`),
    F('asi-8',8,'Zvýšení hodnot vlastností',`Získáš feat Zvýšení hodnot vlastností nebo jiný feat, pro který splňuješ podmínky.`),
    F('daring-strike',9,'Odvážný zásah',`Jednou během každého svého tahu, když zasáhneš tvora útokem zbraní, můžeš způsobit dodatečné zranění rovné jednomu hodu Cool die, pokud platí alespoň jedna podmínka: během tohoto tahu ses pohnul alespoň 10 stop přímou čarou; útok jsi provedl během Indyho skluzu nebo Zhoupnutí; nebo má cíl stav Chycený či Na zemi. Typ dodatečného zranění je stejný jako typ zranění zbraně.`,{action:'Other'}),
    F('relic-arsenal',10,'Arzenál relikvií',`Získáš dvě další relikvie podle své volby. Současně můžeš mít čtyři připravené relikvie a čtyři relikvie v rezervě.`,{kind:'subclass'}),
    F('conserving-charges',10,'Šetření nábojů',`Když by aktivace magického předmětu nebo relikvie utratila jeden nebo více nábojů, hoď d6. Při výsledku 6 se žádné náboje neutratí.`,{kind:'subclass'}),
    F('not-dead-yet',11,'Ještě nejsem mrtvý',`Pokud bys klesl na 0 Životů, aniž bys byl okamžitě zabit, můžeš místo toho klesnout na 1 Život. Poté se můžeš pohnout až o 10 stop bez vyvolání Příležitostných útoků.\n\nJakmile tuto schopnost použiješ, nemůžeš ji použít znovu, dokud nedokončíš Krátký nebo Dlouhý odpočinek.`,{action:'Other',uses:1,recovery:'SR'}),
    F('improved-attack-slide',11,'Vylepšený útočný skluz',`Útočný skluz získá dvě vylepšení.\n\n• Při Útoku v linii můžeš pro zranění každého zásahu po prvním použít jeden hod Cool die místo Kostky zranění zbraně, pokud je to pro tebe výhodnější.\n• Po dokončení Útočného skluzu můžeš jednou za tah okamžitě vstát bez spotřeby Rychlosti.`),
    F('asi-12',12,'Zvýšení hodnot vlastností',`Získáš feat Zvýšení hodnot vlastností nebo jiný feat, pro který splňuješ podmínky.`),
    F('not-a-chance',12,'Ani náhodou',`Když neuspěješ v záchranném hodu, můžeš utratit 1 Bod coolu, hodit Cool die a výsledek přičíst k záchrannému hodu, čímž můžeš neúspěch změnit na úspěch. Pro jeden konkrétní záchranný hod můžeš tuto schopnost použít pouze jednou.`,{action:'Other',cost:1}),
    F('improved-daring',13,'Vylepšený odvážný zásah',`Dodatečné zranění tvého Odvážného zásahu se zvýší na dva hody Cool die.`),
    F('master-relics',14,'Mistr relikvií',`Získáš dvě další relikvie podle své volby. Současně můžeš mít pět připravených relikvií a pět relikvií v rezervě.`,{kind:'subclass'}),
    F('forced-awakening',14,'Vynucené probuzení',`Jednou za Dlouhý odpočinek můžeš aktivovat relikvii, i když už nemá žádné náboje nebo má své omezené použití vyčerpané. Po vyhodnocení efektu utrpíš Psychické zranění rovné třem hodům Cool die; toto zranění nelze žádným způsobem snížit. Poté tuto relikvii nemůžeš znovu použít, dokud nedokončíš Dlouhý odpočinek.`,{kind:'subclass',action:'Other',uses:1,recovery:'LR'}),
    F('improved-narrow-escape',15,'Vylepšený únik o vlásek',`Když používáš Únik o vlásek, hoď dvěma hody Cool die místo jednoho pro určení získaných Dočasných životů a místo 5 stop se můžeš pohnout až o polovinu své Rychlosti.`),
    F('second-wind',15,'Druhý dech',`Jednou za Dlouhý odpočinek, pokud začínáš svůj tah s 0 Životy a nejsi mrtvý, můžeš tuto schopnost použít i se stavem V bezvědomí. Utratíš 2 Body coolu, obnovíš si Životy rovné dvěma hodům Cool die + své úrovni Lovce pokladů a můžeš okamžitě vstát bez spotřeby Rychlosti.`,{action:'Other',cost:2,uses:1,recovery:'LR'}),
    F('asi-16',16,'Zvýšení hodnot vlastností',`Získáš feat Zvýšení hodnot vlastností nebo jiný feat, pro který splňuješ podmínky.`),
    F('legendary-slide',17,'Legendární skluz',`Maximální vzdálenost Indyho skluzu se zvýší na 30 stop a během skluzu můžeš jednou změnit směr až o 90 stupňů.\n\nKdyž zahajuješ Útočný skluz, můžeš utratit 2 Body coolu místo 1 a během stejného skluzu použít Přesný skluz i Útok v linii. Přesný útok může být jedním z hodů na útok provedených v rámci Útoku v linii.`,{action:'Other',cost:2}),
    F('superior-daring',17,'Dokonalý odvážný zásah',`Dodatečné zranění tvého Odvážného zásahu se zvýší na tři hody Cool die.`),
    F('always-on-guard',18,'Vždy ve střehu',`Dokud nemáš stav Vyřazený, žádný hod na útok proti tobě nemůže mít Výhodu.`),
    F('find-a-way',18,'Najdu cestu',`Na začátku svého tahu můžeš utratit 1 Bod coolu a ukončit na sobě stav Chycený nebo Omezený. Poté se můžeš pohnout až o 10 stop bez vyvolání Příležitostných útoků.`,{action:'Free',cost:1}),
    F('epic-boon',19,'Epický dar',`Získáš feat Epický dar nebo jiný feat, pro který splňuješ podmínky.`),
    F('at-right-moment',20,'Ve správný okamžik',`Jednou za kolo, když nepřátelský tvor do 15 stop od tebe získá stav Na zemi nebo Chycený, mine útokem nebo utrpí Kritický zásah, můžeš proti němu okamžitě provést jeden útok zbraní bez použití Reakce.`,{action:'Other'}),
    F('free-trick',20,'Trik zdarma',`První schopnost Lovce pokladů v každém tvém tahu, která by stála 1 Bod coolu, stojí místo toho 0 Bodů coolu.`)
  ];

  const ancientLanguages=['Latina','Starý keltský jazyk','Starý germánský jazyk','Stará řečtina','Egyptština','Hebrejština','Arabština','Perština','Akkadština','Sanskrt','Mandarínština','Nahuatl','Mayské jazyky','Kečuánština'];
  const saves=['DEX','INT'];
  const armor=['Light Armor'];
  const weapons=['Simple Weapons','Martial Ranged Weapons','Martial Finesse Weapons','Whips','Firearms'];
  const pb=l=>l>=17?6:l>=13?5:l>=9?4:l>=5?3:2;
  const coolTotal=l=>l<2?0:Math.max(2,Math.min(20,Number(l)||1));
  const coolDie=l=>l>=16?'d12':l>=10?'d10':l>=5?'d8':'d6';
  const relicLimit=l=>l>=14?[5,5,10]:l>=10?[4,4,8]:l>=6?[3,3,6]:l>=3?[2,2,4]:[0,0,0];
  const hpMax=(l,conMod)=>Math.max(1,10+Number(conMod||0)+(Math.max(1,Number(l)||1)-1)*(6+Number(conMod||0)));

  window.TreasureHunterDataV7s={features,ancientLanguages,saves,armor,weapons,pb,coolTotal,coolDie,relicLimit,hpMax};
})();
