(function(){
  const R=(id,name,level,fullText,action='Passive',charges=0,recovery='LR',extra={})=>({id,name,level,summary:String(fullText||'').split('\n')[0],fullText,action,charges,recovery,...extra});
  window.TreasureHunterRelicsV7s=[
    R('master-thiefs-key','Klíč mistra zlodějů',3,`Klíč nahrazuje Zlodějské náčiní. Když jej používáš, máš Výhodu na ověření vlastnosti k otevření zámku nebo zneškodnění pasti.\n\nKdyž v takovém ověření neuspěješ, můžeš po hodu, ale předtím, než PJ popíše následky, přidat jeden hod Cool die. Tuto druhou vlastnost můžeš použít tolikrát, kolik činí tvůj Bonus zdatnosti, a všechna použití obnovíš po Dlouhém odpočinku.`,`Passive`,0,'LR',{uses:'PB'}),
    R('travelers-talisman','Cestovatelský talisman',3,`Tvá Rychlost se zvýší o 5 stop a nemagický Obtížný terén tě nestojí žádný pohyb navíc.`,`Passive`,0,'LR',{bonusSpeed:5}),
    R('gravity-idol','Modla gravitace',3,`Relikvie má 1 náboj, který obnoví po Dlouhém odpočinku.\n\nTíha středu. Magickou akcí utratíš náboj a zvolíš bod do 60 stop. Až 1 minutu, dokud udržuješ Soustředění, je zem v okruhu 20 stop od tohoto bodu Obtížným terénem pro každého tvora kromě tebe.\n\nKdyž jiný tvor začne svůj tah v oblasti, musí uspět v záchranném hodu na Sílu proti DC relikvie. Při neúspěchu je přitažen 10 stop přímo ke středu oblasti. Tento pohyb nevyvolává Příležitostné útoky.`,`Action`,1),
    R('thunder-idol','Hromová modla',3,`Relikvie má 3 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nHromový výboj. Jednou během každého svého tahu, když zasáhneš tvora útokem zbraní, můžeš utratit 1 náboj. Cíl utrpí dodatečné hromové zranění rovné jednomu hodu Cool die. Je-li cíl Velký nebo menší, můžeš jej navíc odtlačit až 10 stop přímo od sebe.`,`Other`,3),
    R('cat-idol','Kočičí modla',3,`Získáš Vidění ve tmě do 30 stop. Pokud už Vidění ve tmě máš, jeho dosah se zvýší o 30 stop. Do 30 stop vidíš normálně v magické i nemagické Tmě.\n\nMáš Výhodu na ověření Obratnosti (Akrobacie) k udržení rovnováhy a na záchranné hody, kterými se vyhýbáš získání stavu Na zemi.`,`Passive`,0,'LR',{darkvision:30}),
    R('healing-amulet','Léčivý amulet',3,`Relikvie má počet nábojů rovný tvému Bonusu zdatnosti a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nŽivot ještě nevyhasl. Magickou akcí se dotkneš tvora, utratíš 1 náboj a obnovíš mu Životy rovné dvěma hodům Cool die + tvému modifikátoru Inteligence, minimálně 1 Život. Pokud má cíl 0 Životů, Cool die neházej; pro oba hody použij nejvyšší možný výsledek.`,`Action`,0,'LR',{uses:'PB'}),
    R('lucky-coin','Mince štěstěny',3,`Relikvie má 3 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nJeště jednou. Když neuspěješ v ověření vlastnosti, můžeš utratit 1 náboj a hod zopakovat. Musíš použít nový výsledek.`,`Other`,3),
    R('occult-lens','Okultní čočka',3,`Odhalení magie. Dokud je relikvie aktivní, můžeš sesílat Odhalení magie bez pozice kouzla a Materiálních složek, ale pouze s dosahem 5 stop.`,`Action`),
    R('protective-scarab','Ochranný skarabeus',3,`Přízeň bohů. Když provádíš záchranný hod, můžeš po hodu, ale před oznámením výsledku, přidat jeden hod Cool die. Tuto vlastnost můžeš použít jednou za Krátký nebo Dlouhý odpočinek.`,`Other`,1,'SR'),
    R('guardians-signet-ring','Pečetní prsten strážce',3,`Odkloněný zásah. Když tě zasáhne hod na útok, můžeš Reakcí zvýšit své Obranné číslo o 1d6 do začátku svého příštího tahu, včetně proti spouštěcímu útoku. Zvýšení může způsobit, že útok mine. Tuto vlastnost můžeš použít jednou za Krátký nebo Dlouhý odpočinek.`,`Reaction`,1,'SR'),
    R('ashes-unseen-procession','Popel neviditelného průvodu',3,`Relikvie má 2 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nZávoj popela. Bonusovou akcí utratíš 1 náboj a zvolíš bod do 30 stop. Do začátku tvého příštího tahu je koule o poloměru 10 stop kolem tohoto bodu Silně zahalená. Silný vítr popel okamžitě rozptýlí.`,`Bonus Action`,2),
    R('ancient-mariners-compass','Kompas dávného mořeplavce',3,`Pravý směr. Vždy víš, kde je sever, znáš svou přibližnou nadmořskou výšku nebo hloubku a nemagické efekty nemohou způsobit, že se ztratíš. Ty a tvorové cestující do 30 stop od tebe máte Výhodu na ověření Moudrosti (Přežití) k navigaci.\n\nJednou za Dlouhý odpočinek můžeš kompas 1 minutu studovat a pojmenovat místo, které jsi navštívil a které leží do 10 mil. Po dobu 1 hodiny kompas ukazuje podél nejbližší průchozí cesty k tomuto místu, ale nezohledňuje pohybující se nebezpečí.`,`Passive`,1),
    R('silent-pocket-watch','Tiché hodinky',3,`Ani o vteřinu později. Máš Výhodu na hody Iniciativy.`),
    R('bell-last-guardian','Zvonek posledního strážce',3,`Relikvie má 2 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nZlověstné zazvonění. Bonusovou akcí utratíš 1 náboj. Do začátku tvého příštího tahu nemůže žádný jiný tvor do 15 stop od tebe, který zvonek slyší, používat Reakce.`,`Bonus Action`,2),

    R('ruby-eyed-heron','Volavka s rubínovýma očima',6,`Požadavek: Lovec pokladů 6. úrovně.\n\nRelikvie má 2 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nZlověstné zvonění. Bonusovou akcí utratíš 1 náboj a zvolíš jeden typ tvora: Aberace, Zvíře, Nebešťan, Elementál, Víla, Běs, Monstrum nebo Nemrtvý. Poté zvolíš Nebezpečné přitahování nebo Nepřirozené odpuzování.\n\nAž 1 minutu, dokud udržuješ Soustředění, vydává volavka tiché zlověstné zvonění slyšitelné do 30 stop. Efekt skončí dříve, pokud relikvii znovu aktivuješ.\n\nKdykoli tvor zvoleného typu, který zvonění slyší, začne svůj tah do 30 stop od relikvie, musí uspět v záchranném hodu na Moudrost proti DC relikvie. Při neúspěchu se okamžitě pohne až o 10 stop nejkratší dostupnou cestou určenou aktivním efektem: Nebezpečné přitahování směrem k relikvii; Nepřirozené odpuzování směrem od relikvie.\n\nTento pohyb se počítá do pohybu tvora v daném tahu a nevyvolává Příležitostné útoky. Pohyb skončí dříve, pokud se tvor nemůže k relikvii přiblížit nebo se od ní vzdálit. Relikvie ti neodhaluje polohu ovlivněných tvorů.`,`Bonus Action`,2),
    R('talisman-mute-monk','Talisman němého mnicha',6,`Požadavek: Lovec pokladů 6. úrovně.\n\nRelikvie má 2 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nPosvátné ticho. Magickou akcí utratíš 1 náboj a zvolíš bod do 60 stop. Až 1 minutu, dokud udržuješ Soustředění, obklopuje tento bod koule ticha o poloměru 20 stop. Uvnitř koule nelze vytvořit zvuk ani skrz ni zvuk nemůže procházet a nelze v ní používat Verbální složky. Dokud efekt trvá, máš stav Ohlušený.`,`Action`,2),
    R('jade-key','Nefritový klíč',6,`Požadavek: Lovec pokladů 6. úrovně.\n\nRelikvie má 2 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nNic nezůstane zamčené. Magickou akcí utratíš 1 náboj, dotkneš se dveří, brány, okna nebo zavřené nádoby a otevřeš jeden nemagický zámek. Proti magickému zámku utratíš 2 náboje a provedeš ověření Inteligence (Arkány) proti DC záchrany daného efektu; při úspěchu jej potlačíš na 1 hodinu. Tato vlastnost neodstraní závoru ani jinou fyzickou překážku, která není zámkem.`,`Action`,2),
    R('lantern-true-flame','Lucerna pravdivého plamene',6,`Požadavek: Lovec pokladů 6. úrovně.\n\nRelikvie má 1 náboj, který obnoví po Dlouhém odpočinku.\n\nSvětlo pravdy. Magickou akcí utratíš náboj a rozsvítíš lucernu na 10 minut. Vydává Jasné světlo do 15 stop a Tlumené světlo dalších 15 stop. Dokud stojíš v jejím Jasném světle, nemůžeš vědomě vyslovit lež.\n\nKdyž jiný tvor poprvé v tahu vstoupí do Jasného světla nebo v něm začne svůj tah, provede záchranný hod na Charisma proti DC relikvie. Při neúspěchu nemůže vědomě lhát, dokud ve světle zůstává. Ví, že je ovlivněn, a může odpovídat vyhýbavě. Při úspěchu je vůči této aktivaci lucerny imunní.`,`Action`,1),
    R('jailers-chain','Žalářníkovo pouto',6,`Požadavek: Lovec pokladů 6. úrovně.\n\nRelikvie má 2 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nOkovy bez zámku. Když zasáhneš tvora útokem zbraní, můžeš utratit 1 náboj. Jeho Rychlost se sníží o 10 stop do začátku tvého příštího tahu.\n\nJe-li cíl Velký nebo menší, provede navíc záchranný hod na Sílu proti DC relikvie. Při neúspěchu získá stav Omezený do začátku tvého příštího tahu.`,`Other`,2),
    R('censer-ashen-dragon','Kadidelnice popelavého draka',6,`Požadavek: Lovec pokladů 6. úrovně.\n\nRelikvie má 3 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nSpalující dech. Magickou akcí utratíš 1 náboj a vyšleš žár v kuželu 15 stop. Každý tvor v oblasti provede záchranný hod na Obratnost proti DC relikvie. Při neúspěchu utrpí Ohnivé zranění rovné třem hodům Cool die, při úspěchu polovinu. Hořlavé předměty v oblasti, které nikdo nenosí ani nedrží, vzplanou.`,`Action`,3),
    R('amulet-twisted-fate','Amulet pokřiveného osudu',6,`Požadavek: Lovec pokladů 6. úrovně.\n\nRelikvie má 3 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nZlé znamení. Jednou během každého svého tahu, když zasáhneš tvora útokem zbraní, můžeš utratit 1 náboj. Cíl je tebou prokletý do začátku tvého příštího tahu. První hod na útok, který předtím provede, se sníží o jeden hod Cool die a kletba poté skončí. Dokud je tímto způsobem prokletý, nemůže obnovovat Životy.`,`Other`,3),
    R('ring-feathered-serpent','Prsten opeřeného hada',6,`Požadavek: Lovec pokladů 6. úrovně.\n\nRelikvie má 1 náboj, který obnoví po Dlouhém odpočinku.\n\nVzestup. Magickou akcí utratíš 1 náboj, otočíš prsten tak, aby jeho horní strana směřovala k dlani, a zvolíš bod do 25 stop. Na 1 minutu, dokud udržuješ Soustředění, přestane v okruhu 20 stop od tohoto bodu působit gravitace a každý tvor, včetně tebe, který je v oblasti nebo do ní poprvé vstoupí, začne levitovat. Tento pohyb nevyvolává Příležitostné útoky.\n\nNa konci svého tahu tvor stoupne: Drobný a Malý o 15 stop, Střední a Velký o 10 stop, Obrovský nebo větší o 5 stop. Takto nemůže vystoupat nad 60 stop. Levitující tvor se nemůže pohybovat vodorovně, pokud nemá v dosahu něco, od čeho se může odrazit. Tvor s Rychlostí létání se může pohybovat libovolným směrem.\n\nNa začátku svého tahu může každý levitující tvor provést záchranný hod na Charisma proti DC relikvie. Při úspěchu efekt pro něj skončí; spadne, utrpí 1d6 Drtivého zranění za každých 10 stop pádu a získá stav Na zemi. Poté už jej tato aktivace relikvie neovlivňuje.`,`Action`,1),
    R('obsidian-tablet','Obsidiánová destička',6,`Požadavek: Lovec pokladů 6. úrovně.\n\nRelikvie má 3 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nKletby vytesané do kamene. Na destičce jsou ve starověkém jazyce vytesány tři kletby. Magickou akcí můžeš utratit 1 náboj, jednu z nich nahlas přečíst a zvolit tvora, kterého vidíš do 30 stop. Stejnou kletbu nemůžeš použít znovu, dokud nedokončíš Dlouhý odpočinek.\n\nÚnava. Cíl musí uspět v záchranném hodu na Charisma proti DC relikvie, jinak je až 1 minutu prokletý, dokud udržuješ Soustředění. Jeho Rychlost je poloviční, nemůže používat Reakce a ve svém tahu může provést buď Akci, nebo Bonusovou akci, ne obojí. Na konci každého tahu záchranu opakuje. Pokud uspěje už v první záchraně, jeho Rychlost je do začátku tvého příštího tahu snížena o 10 stop.\n\nPekelná smůla. Cíl provede záchranný hod na Charisma proti DC relikvie. Při neúspěchu má Nevýhodu na všechny hody na útok až 1 minutu, dokud udržuješ Soustředění, a na konci každého tahu záchranu opakuje. Při úspěchu má Nevýhodu pouze na první hod na útok před začátkem tvého příštího tahu.\n\nDotek smrti. Cíl provede záchranný hod na Charisma proti DC relikvie. Při neúspěchu utrpí 5d6 Nekrotického zranění a jeho maximum Životů se sníží o stejné množství do dokončení Dlouhého odpočinku. Při úspěchu utrpí poloviční zranění a maximum Životů se nesníží. Odstranění kletby ukončí jednu trvající kletbu této relikvie nebo odstraní snížení maxima Životů, ale neobnoví již ztracené Životy.`,`Action`,3),

    R('helm-defeated-warlord','Přilba poraženého vojevůdce',10,`Požadavek: Lovec pokladů 10. úrovně.\n\nTuto relikvii můžeš použít jednou za Dlouhý odpočinek.\n\nAura porážky. Akcí si přilbu nasadíš a aktivuješ. Efekt trvá až 1 minutu, dokud udržuješ Soustředění, a obklopuje tě aura o poloměru 15 stop.\n\nKdyž nepřátelský tvor poprvé v tahu vstoupí do aury nebo v ní začne svůj tah, provede záchranný hod na Moudrost proti DC relikvie. Při neúspěchu získá stav Vystrašený do začátku svého příštího tahu. Dokud efekt trvá, tvá Rychlost je snížena o 10 stop.`,`Action`,1),
    R('thunderbird-statuette','Soška hromového ptáka',10,`Požadavek: Lovec pokladů 10. úrovně.\n\nV hrudi sošky je místo srdce zasazen velký modrý drahokam, který soustřeďuje sílu bouřkových mraků. Relikvie má 2 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nHrom. Akcí utratíš 1 náboj a zvolíš bod na zemi do 60 stop. Náhlé zahřátí a prudké rozpínání vzduchu vytvoří hlasitou tlakovou vlnu. Každý tvor do 5 stop od zvoleného bodu provede záchranný hod na Obratnost proti DC relikvie.\n\nPři neúspěchu utrpí 5d8 Thunder damage a získá stav Na zemi. Při úspěchu utrpí poloviční zranění a stav Na zemi nezíská. Hrom je slyšitelný do 300 stop.`,`Action`,2),
    R('sun-disk','Sluneční disk',10,`Požadavek: Lovec pokladů 10. úrovně.\n\nTuto relikvii můžeš použít jednou za Dlouhý odpočinek.\n\nSpalující úsvit. Magickou akcí vyšleš světlo v kuželu 30 stop. Tvorové v oblasti provedou záchranný hod na Obratnost proti DC relikvie. Při neúspěchu utrpí Zářivé zranění rovné čtyřem hodům Cool die a získají stav Oslepený do začátku tvého příštího tahu. Při úspěchu utrpí poloviční zranění a stav Oslepený nezískají.`,`Action`,1),
    R('candle-stilled-shadows','Svíce nehybných stínů',10,`Požadavek: Lovec pokladů 10. úrovně.\n\nRelikvie má 2 náboje a všechny utracené náboje obnoví po Dlouhém odpočinku.\n\nNehybné stíny. Magickou akcí utratíš 1 náboj a zvolíš bod do 60 stop. Až 1 minutu, dokud udržuješ Soustředění, je oblast do 10 stop od tohoto bodu Obtížným terénem. Když tvor začne svůj tah v oblasti, provede záchranný hod na Obratnost proti DC relikvie. Při neúspěchu získá stav Omezený do začátku svého příštího tahu.`,`Action`,2),
    R('nail-black-coffin','Hřebík z černé rakve',10,`Požadavek: Lovec pokladů 10. úrovně.\n\nRána do duše. Jednou během každého svého tahu, když zasáhneš tvora útokem zbraní na blízko, způsobíš mu navíc 1d6 Nekrotického nebo Psychického zranění podle své volby.`),
    R('cloak-pilgrim-worlds','Plášť poutníka mezi světy',10,`Požadavek: Lovec pokladů 10. úrovně.\n\nProměnlivá ochrana. Kdykoli dokončíš Dlouhý odpočinek, zvol Kyselinové, Chladné, Ohnivé, Bleskové, Nekrotické, Jedové, Psychické nebo Thunder damage. Vůči zvolenému typu zranění máš Odolnost, dokud nezvolíš znovu.`,`Passive`,0,'LR',{choice:'damageResistance'}),

    R('idol-aztec-serpent-god','Modla aztéckého hadího boha',13,`Požadavek: Lovec pokladů 13. úrovně.\n\nTuto relikvii můžeš použít jednou za Dlouhý odpočinek.\n\nPřízračný stisk. Magickou akcí zvol Velkého nebo menšího tvora, kterého vidíš do 60 stop. Jeho Rychlost je 0 do začátku tvého příštího tahu. Cíl zároveň provede záchranný hod na Sílu proti DC relikvie. Při neúspěchu získá stav Paralyzovaný až na 1 minutu, dokud udržuješ Soustředění. Na konci každého svého tahu může záchranu opakovat a při úspěchu efekt ukončí.`,`Action`,1),
    R('book-unwritten-paths','Kniha nenapsaných cest',13,`Požadavek: Lovec pokladů 13. úrovně.\n\nTuto relikvii můžeš použít jednou za Dlouhý odpočinek.\n\nCesty, které nikdy nebyly. Magickou akcí zvol počet tvorů do 30 stop od sebe až do výše svého modifikátoru Inteligence, minimálně jednoho. Každý cíl přemístíš do neobsazeného prostoru, který vidíš do 60 stop.\n\nOchotný tvor je přemístěn automaticky. Neochotný Velký nebo menší tvor provede záchranný hod na Charisma proti DC relikvie a při úspěchu přemístěn není. Po aktivaci je tvá Rychlost do konce tahu 0.`,`Action`,1),
    R('horn-empty-tomb','Roh prázdné hrobky',13,`Požadavek: Lovec pokladů 13. úrovně.\n\nTuto relikvii můžeš použít jednou za Dlouhý odpočinek.\n\nHlas hrobky. Magickou akcí zatroubíš do kuželu 30 stop. Každý tvor v oblasti, který roh slyší, provede záchranný hod na Moudrost proti DC relikvie. Při neúspěchu utrpí Psychické zranění rovné pěti hodům Cool die a získá stav Vystrašený až na 1 minutu, dokud udržuješ Soustředění. Při úspěchu utrpí poloviční zranění a stav Vystrašený nezíská. Na konci každého tahu může ovlivněný tvor záchranu opakovat a při úspěchu efekt ukončí. Dokud udržuješ Soustředění, máš stav Ohlušený.`,`Action`,1),
    R('blood-dagger','Krvavá dýka',13,`Požadavek: Lovec pokladů 13. úrovně.\n\nŽiví se neštěstím. Jednou během každého svého tahu, když způsobíš zranění tvorovi, který je Zkrvavený, získáš Dočasné životy rovné svému Bonusu zdatnosti.`),

    R('eye-dead-seer','Oko mrtvého věštce',18,`Požadavek: Lovec pokladů 18. úrovně.\n\nZrak za závojem. Máš Pravé vidění do 30 stop.`,`Passive`,0,'LR',{truesight:30}),
    R('atlas-nonexistent-road','Atlas neexistující cesty',18,`Požadavek: Lovec pokladů 18. úrovně.\n\nTuto relikvii můžeš použít jednou za Dlouhý odpočinek.\n\nÚnik z mapy. Magickou akcí zvol sebe a počet ochotných tvorů do 30 stop od sebe až do výše svého modifikátoru Inteligence, minimálně jednoho. Všechny cíle teleportuješ na místo ve stejné sféře existence, které jsi osobně navštívil a je do 100 mil. Každý cíl se objeví v nejbližším vhodném neobsazeném prostoru.`,`Action`,1),
    R('last-exorcists-testament','Závěť posledního exorcisty',18,`Požadavek: Lovec pokladů 18. úrovně.\n\nZapečetěná duše. Jsi imunní vůči stavům Okouzlený a Vystrašený. Jednou za Dlouhý odpočinek, když by na tebe měla působit kletba, můžeš způsobit, že na tebe nebude mít žádný účinek. U unikátní příběhové kletby může PJ rozhodnout, že je její účinek místo toho potlačen do dokončení tvého příštího Dlouhého odpočinku.`,`Passive`,1),
    R('heart-eclipse','Srdce zatmění',18,`Požadavek: Lovec pokladů 18. úrovně.\n\nRelikvie má 1 náboj, který obnoví po Dlouhém odpočinku.\n\nČerné slunce. Magickou akcí utratíš náboj a zvolíš bod do 120 stop. Až 1 minutu, dokud udržuješ Soustředění, obklopuje tento bod koule magické Tmy o poloměru 30 stop. Ty a počet tvorů podle své volby až do výše modifikátoru Inteligence, minimálně jeden, skrz tuto Tmu vidíte. Ostatní tvorové uvnitř mají poloviční Rychlost a nemohou používat Reakce. Kdykoli tvor začne svůj tah uvnitř koule, provede záchranný hod na Moudrost proti DC relikvie. Při neúspěchu utrpí Psychické zranění rovné čtyřem hodům Cool die.`,`Action`,1),
    R('coffer-final-judgment','Schrána posledního soudu',18,`Požadavek: Lovec pokladů 18. úrovně.\n\nPozlacená schrána ukrývá moc, kterou by žádný smrtelník neměl spatřit. Když se víko otevře, zbývá jediná rozumná rada: zavři oči.\n\nRelikvie má 1 náboj, který obnoví po Dlouhém odpočinku.\n\nNedívej se. Akcí utratíš 1 náboj a otevřeš schránu. Každý tvor do 30 stop, který na ni má přímý výhled, včetně tebe, provede záchranný hod na Obratnost proti DC relikvie, aby včas zavřel oči nebo odvrátil pohled.\n\nPři úspěchu se tvor pohledu vyhne, ale získá stav Oslepený do začátku tvého příštího tahu. Při neúspěchu utrpí 10d8 Zářivého zranění a získá stav Omráčený do začátku tvého příštího tahu. Tvor, který už má stav Oslepený nebo schránu nemůže vidět, není ovlivněn.`,`Action`,1)
  ];
})();
